### ISSUE TITLE
(3/15 마감) 삼성전자 DS부문 혁신센터에서 2023년 상반기 3급 공개채용

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#103]
채용정보같은것도 공유해볼 수 있을까요?

----------

삼성전자 DS부문 혁신센터에서 2023년 상반기 3급 공개채용을 진행합니다!

삼성전자 DS부문의 Data와 IT인프라 솔루션을 담당하여 IT서비스 고도화와 Digital Transformation을 선도하다.

끊임없이 성장하는 혁신센터에서 저희와 함께 Digital Transformation을 실현해나가실 여러분들의 많은 관심과 지원 부탁드립니다:)

 

서류 접수 기간 : 3월 8일 수요일 ~ 3월 15일 수요일 17:00

서류 접수 사이트 : 삼성커리어스닷컴 [www.samsungcareers.com](http://www.samsungcareers.com/) 

                         *자세한 지원 방법 및 Job Description 확인 가능

DS부문 & 사업부 소개 홈페이지 : https://www.samsung-dsrecruit.com/index.php 

                                           *직무別 임직원 인터뷰 및 직무추천서비스 제공

 

혁신센터는 DS부문의 Data와 IT 담당 조직으로 DS부문의 SW&IT Governance 수행 및 전략을 수립하고 모든 사업 영역에 걸쳐 IT인프라와 Data 서비스를 개발, 운영합니다. Data Center 구축 및 서버/네트워크 고도화와 AI, ML, DL 등의 전문 데이터 처리 기법을 활용하여 자동화, 지능화 Factory 구축합니다. AI 및 시뮬레이션 기술을 적용하여 반도체 불량 예측 및 공정 개발에 기여합니다. Digital Transformation을 선도하여 무결점 서비스, 초자동화, 미래 예측, 디지털 민첩성, Data와 SW중심으로 일하는 새로운 문화와 경험을 창출합니다.

**Comment by wheresmadog** [comment]
Apart from this very issue, perhaps we can add a new channel for job info?

**Comment by d-h-lee** [comment]
@wheresmadog @wy-july Please go ahead and add a new public channel for job info. Let's see how it runs!
