### ISSUE TITLE
한국정보과학회 정기학술대회 KCC 2023 (연1회 이벤트)

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#109]
좋은 정보 공유 감사합니다 @cth127 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/55645287/226809512-6be95390-e125-439b-9114-93e2e7e7b1c8.png">

논문 접수와 관련된 디테일은 아래 링크에 있습니다:
https://www.kiise.or.kr/conference/main/getContent.do?CC=kcc&CS=2023&content_no=1725&PARENT_ID=020100

일정은
<img width="637" alt="image" src="https://user-images.githubusercontent.com/55645287/226811323-7270c6dd-7fb7-4a89-a665-801bb353befc.png">

요령 및 주의사항은
<img width="637" alt="image" src="https://user-images.githubusercontent.com/55645287/226811348-8d2a7809-64dd-4826-b669-3b002efe04f0.png">

국제학회/논문에 낼 정도의 각을 보고 있다면 조심해야될것이.. 여기 낸 것을 그대로 다른 학회에 재활용하지 못한다는 점입니다.

작년도 접수된 논문 통계를 보면 [원문](https://www.kiise.or.kr/conference/dissertation/dissertationStatistics.do?CC=kcc&CS=2022&PARENT_ID=020500)
<img width="737" alt="image" src="https://user-images.githubusercontent.com/55645287/226809664-2fd1fe7b-4c36-4b53-b23d-914e67e3d4a4.png">

상도 준다는군요.. 그리고 상 받음을 연구실에서도 자랑도 합니다 [예시](http://nlp.konkuk.ac.kr/bbs/board.php?bo_table=Notice&wr_id=116&sst=wr_datetime&sod=desc&sop=and&page=1)
<img width="818" alt="image" src="https://user-images.githubusercontent.com/55645287/226809985-29102f7d-a66f-4f29-9d8f-e0be6ab0a8a5.png">

**Comment by pinga999** [comment]
https://www.dbpia.co.kr/journal/publicationDetail?publicationId=PLCT00000760
