### ISSUE TITLE
epoxy, eq KICK-OFF (rescheduling: on or after Apr 5)

### ISSUE THREAD

**Issue by pinga999** [AIML-K/bamboo-forest#112]
place : TBD
time :  ~~03.29 19:00~~ TBD

details will be announced!

**Comment by wheresmadog** [comment]
Is everyone supposed to attend?

**Comment by d-h-lee** [comment]
킥오프 미팅을 준비하기가 쉽지 않네요. 다음주 (4/5 이후) 로 시간을 조정하려고 합니다;;

**Comment by invigorator96** [comment]
4월 5일이 지났는데 이 건은 언제로 생각하고 있으면 될까요?

**Comment by d-h-lee** [comment]
#117 여기에서 스케쥴 정하도록 할께요~

**Comment by d-h-lee** [comment]
어린이날과 스승의날 사이에!
