### ISSUE TITLE
4/3 (Tue) visiting SNU 

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#113]
에폭시 과제 연구진행을 위해서 서울대학교로 연구출장을 갑니다. 

관심있는 분들은 내일 (4/3 화) 오전 10시, 서울대학교 관악캠퍼스 200동 1층에서 만나요. 

오시는 분들은 코멘트 달아주세요. 참석인원 가늠을 하려고 합니다.

**Comment by wy-july** [comment]
참석합니다

**Comment by invigorator96** [comment]
참석합니다

**Comment by prism4304** [comment]
참석합니다

**Comment by JeongYejin1226** [comment]
참석합니다

**Comment by choi430** [comment]
참석합니다

**Comment by d-h-lee** [comment]
잘 다녀왔습니다. 다들 수고 많았어요!

![20230404_114304](https://user-images.githubusercontent.com/55645287/230276268-3a8beffa-dcf8-48f6-8971-d23ced4bea9f.jpg)
@invigorator96
