### ISSUE TITLE
4/26 Townhall Meeting (all grads strongly recommended to attend)

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#117]
Apparently in the midterm week, the largest number of grad students can get together.

Nice timing. Also, the last piece of information to discuss the spring-summer schedule just got in: Open Track AI Grand Challenge

So we have three key themes for the 1st half of 2023:

- Earthquake
- Epoxy
- AI Grand Challenge

-------

<img width="585" alt="image" src="https://user-images.githubusercontent.com/55645287/234153327-3146d6e8-d5b5-4d1e-93e4-4b68872ee32b.png">

<Open Track>

Open Track은 대회 공고 이후 접수한 참가팀 모두 참여할 수 있으며, **대회 문제와 유형은 1단계와 동일합니다.**

※ 공고 예정일 : 5월 초~중순

- 대회 개최 후 1단계 상위팀의 결과를 바탕으로 Open Track의 우승팀을 결정하게 되며 우승팀은 본대회 진출 자격이 주어집니다.  
- 1단계에서 아쉽게 우수팀으로 선정되지 못하셨다면 이번 대회에 꼭 참석하셔서 더욱 좋은 성과를 이루실 수 있도록 기원합니다.

**Comment by pinga999** [comment]
AGC관련 부가적 정보
'기술교류회' 라는게 보이네요?

>![1682490198121.jpg](https://user-images.githubusercontent.com/76512129/234487314-539c9f8e-4aed-496c-bc83-5ed5d5ad6bda.jpg)
