### ISSUE TITLE
Refrigerator will be arriving

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#119]
Looks like it will arrive sometime this week. I will update the exact date once I get informed.

Model: https://front.homeplus.co.kr/item?itemNo=10000301725097&storeType=ds

**Comment by d-h-lee** [comment]
Delivery time estimate: between 1PM and 2PM, on 5/3 Wednesday.

Please prepare a space to welcome the fridge.

**Comment by hamgcho** [comment]
![20230503_143519](https://user-images.githubusercontent.com/68200616/235839265-2cdbc3c7-5c2d-4590-9941-9460ee465e8b.jpg)

도착했습니다
