### ISSUE TITLE
6/14 네트워크 증설 사전탐방/견적 

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#125]
네트워크 증설 관련해서 업체가 사전탐방/견적작업으로 6/14 (수) 방문합니다. 오후2시 예정입니다.

네트워크 업그레이드 방향이라든지, 건의사항이 있으면 코멘트 달아주세요.

**Comment by hojun-y** [comment]
가능하면 연구실 안쪽으로도 wired network를 사용할 수 있게 되면 좋겠습니다.
Wireless connection만 사용하니 간혹 connection이 불안정할 때 workstation의 wifi 연결 구성이 바뀌면서 IP address가 바뀐 적이 종종 있었는데 그 부분이 살짝 불편했습니다.

**Comment by d-h-lee** [comment]
연구실 안쪽으로 wired 증설은 못했지만;; 견적을 낸 네트워크 정비작업은 일단 완료했습니다. 

다음번 네트워크 증설작업은 내년 예정입니다. 추가 건의사항들도 지속적으로 취합하고 있으니 알려주세요~

**Comment by invigorator96** [comment]
Active issue: <https://github.com/AIML-K/Admin/issues/5>

(네트워크 관리자만 볼 수 있는 이슈입니다)

가 아직 해결이 안 된 게 있습니다. 기존 사용하던 공유기쪽 이슈로 보이긴 하는데... 하드웨어 추가 혹은 교체가 필요할 수 있습니다.
