### ISSUE TITLE
6/21 Wednesday meeting stack

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#126]
Summer schedule begins!

- [ ] #127
- [ ] 6/21 2-3pm Epoxy
- [ ] #128
- [ ] 6/21 4-5pm Townhall

**Comment by d-h-lee** [comment]
@d-h-lee 는 오늘 미팅 타운홀만 참석합니다. 다른 분들도 참석여부 알려주세요.

**Comment by Ricepunchb** [comment]
@Ricepunchb 2:00~4:45 기말고사 관계로 불참합니다.. :(
