### ISSUE TITLE
6/21 1-2pm AGC

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#127]
@AIML-K/grads 관심있는분들 필참입니다. 참석 전에 사전설명회 및 문제정의서 살펴보고 와주세요.

@cth127 리드 부탁합니다. 오늘 커버할 내용들도 간단히 여기 알려주세요

**Comment by d-h-lee** [comment]
연구실 줌미팅방에도 연결해서 스크린셰어 걸고 미팅 진행해주세요~

**Comment by cth127** [comment]
To cover

1. 문제 정의서 스키밍 및 질의 응답
2. Open domain QA, Chart QA 등 2022년 SOTA 간략히 소개
3. 2022 모델 Draft 소개 및 질의응답

**Comment by cth127** [comment]
Summary

상위권 팀과 우리 팀의 가장 큰 차이는, 우리는 없는 Task를 풀기 위해 있는 Model들을 하드코딩으로 조합했다면 
(T2) 프롬프팅, 복수 정답의 경우 기존 문맥에서 지워가며 and 쉼표로 나눠가며 QA
(T3) ruld-based 테이블 축소
(T4) 문제를 반으로 나눠 각각 QA

상위권 팀의 경우 없는 Task를 풀기 위해 있는 Data를 조합하여 Model을 훈련시켰다.
(T2) Table QA 데이터를 Structured text qa 데이터로 변환
(T4) 있는 Table을 쪼개는 등을 통해 Context length가 큰 BigBird 모델에 훈련

이번엔 상위권 팀과 비슷한 접근 방식을 취해야 할 것 같다.

단기 로드맵.
(T2) Table QA 데이터를 Structured text qa 데이터로 변환하여 훈련
(T3) 숫자가 많은 Table, 큰 Table 등을 Augment하여 훈련
(T3) 강필성 교수님 연구실에서 공개한 Korean-pretrained Tapas 사용
(T4) 있는 Table을 쪼개는 등을 통해 Context length가 큰 BigBird 모델에 훈련

장기 로드맵
(T3) ChartQA를 위한 Data와 End-to-End Model 개발
