### ISSUE TITLE
Tool to share a large file, cross platform, to anyone, with low maintenance

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#13]
큰 파일 공유를 어떻게 할까 고민했는데, 
- secure 해야되고 무결성 보장. 하지만 로그인정보 셋팅 필요하고 다운/업 사이드 모두 관리필요: scp
- 언제나 다운받기 쉽고 무결성 있지만 로그인정보 셋팅 + 도커사용: docker hub
- secure하지는 않지만 언제나 어디서나 다운받기 쉽고 로그인필요 없음: *이 방법* 이 필요합니다.

**Comment by invigorator96** [comment]
구글 드라이브를 통하는 방법은 큰 파일 공유할 때 너무 느리지 않을까요..? 얼마나 크냐의 문제이긴 하겠지만 저번에 데이터셋 10시간씩 다운받고 했던 기억이...

**Comment by d-h-lee** [comment]
네네 단일 파일 아니면 엄청 오래걸립니다. 그런데 이걸로 하면 간단히 1GB정도까지는 큰 부담없이 공유가 되더라구요. 생각하고 있는 것은... 트레이닝 된 모델 파일! 아니면 여럿이 데모해볼만한 데이터셋의 일부분 정도?

**Comment by d-h-lee** [comment]
이건 아마 다시 살려야 하겠군요.. 지금 dockerhub를 통해서 공유가 가능은 한데, 실제 연구실에서 사용하는 상황에 대비해서 어떤 것들로 가는게 좋을지 이야기해봅시다

**Comment by cth127** [comment]
아무래도 있는 NAS를 사용하는 게 가장 맞지 않을까요?

폴더 경로, 태그 등에 대한 컨센서스를 정할 필요가 있어 보입니다.

**Comment by d-h-lee** [comment]
> 아무래도 있는 NAS를 사용하는 게 가장 맞지 않을까요?

그것도 좋겠습니다. 지금 dockerhub에 계정 추가등록이 막혀있는데, 돈을 줘도 안되네요.
