### ISSUE TITLE
Wifi and Linux issue

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#130]
Recent workstations were reported to have wifi issues.

What is the current state? We have 2023-gen1 (white narrow ones) and 2023-gen2 (black wide ones). 

At least the following info is needed. If there is an internal document on this, can anyone let @d-h-lee know?

- Each gen's wifi chipset
- Tested on which Linux (type/version)

**Comment by invigorator96** [comment]
For `2023-gen1`, 

- wifi chipset: MEDIATEK mt7921e
- OS: Ubuntu 20.04 LTS

**Comment by d-h-lee** [comment]
Thanks!

**Comment by d-h-lee** [comment]
Closing, as resolved in https://github.com/AIML-K/Admin/issues/4
