### ISSUE TITLE
Adjustment of 2023-fall semester townhall time(Finish by 08/29)

### ISSUE THREAD

**Issue by pinga999** [AIML-K/bamboo-forest#131]
Please write down the time when you can't participate due to your personal schedule!

Please `check the slots below` when it's not available for each day of the week!
ex) 
- [ ]  $\rightarrow$ ![image](https://github.com/AIML-K/bamboo-forest/assets/76512129/6c31e4e3-ebc9-4246-a9c3-d1bf7e231ca3)

If it's already checked, don't **uncheck** it, and if there's a space that's not checked, you can check it if it's impossible!

And  apart from the check, `please leave an individual comment about the impossible time` as well possible!

**Comment by pinga999** [comment]
Monday

- [ ] 12:00-13:00
- [ ] 13:00-14:00
- [ ] 14:00-15:00
- [ ] 15:00-16:00
- [ ] 16:00-17:00
- [ ] 17:00-18:00

Tuesday

- [ ] 12:00-13:00
- [ ] 13:00-14:00
- [ ] 14:00-15:00
- [ ] 15:00-16:00
- [ ] 16:00-17:00
- [ ] 17:00-18:00

Wednesday

- [ ] 12:00-13:00
- [ ] 13:00-14:00
- [ ] 14:00-15:00
- [ ] 15:00-16:00
- [ ] 16:00-17:00
- [ ] 17:00-18:00

Thursday

- [ ] 12:00-13:00
- [ ] 13:00-14:00
- [ ] 14:00-15:00
- [ ] 15:00-16:00
- [ ] 16:00-17:00
- [ ] 17:00-18:00

Friday


- [ ] 12:00-13:00
- [ ] 13:00-14:00
- [ ] 14:00-15:00
- [ ] 15:00-16:00
- [ ] 16:00-17:00
- [ ] 17:00-18:00

**Comment by Ricepunchb** [comment]
가을학기 수업으로 인해 월, 수 12~16시는 불가합니다

**Comment by jungchanghae** [comment]
impossible time

Tuesday
13:30~14:45

Thursday
13:30~14:45

**Comment by hojun-y** [comment]
아직 수강 정정이 완료되지 않아 월-목 일정은 확정되지 않았으나, 09-18시 대부분 시간이 나지 않을 것 같습니다.
이 부분은 확정되는 대로 comment를 update하겠습니다.

금요일의 경우, 13-17시에 일정이 잡혀 있습니다.

**Comment by cth127** [comment]
매일 오전 및 금요일 3시 이후 제외하면 모두 가능합니다.

**Comment by JeongYejin1226** [comment]
오전 및 화요일 3시 이후 제외하면 모두 가능합니다.

**Comment by pinga999** [comment]
- [ ] 수요일 16:00-18:00 공간대여 (고정)(학기중)

**Comment by pinga999** [comment]
수요일 16:00 - 18:00 공간대여 완료했습니다.

2023-2학기 Townhall 미팅은 일단은 **수요일 16:00 - 18:00**중으로 진행합니다
