### ISSUE TITLE
0906 town-hall memo

### ISSUE THREAD

**Issue by pinga999** [AIML-K/bamboo-forest#132]
# 0906 TownHall

## 안-건
- ~640 전등교체(행정실 전달완료)~

- TownHall time Fix
    - 16:30(FIX)
- Workshop(09/15) 추진위?(진행위?) --> #133 
    - 진행상황?
        - 유임순홀 확보 완료
    - **Topic 안보낸분 0906내로 반드시 보낼것(Title(가제)적어서 전달)**
        - 아니면 **조직위(진행위?)**
    - 큰 주제
        - 과제단위(AGC,Epoxy,EQ etc..)
        - 개인연구
        - 흥미로운 Theme
    - 현재 예정된 리허설 X
        - 09/08 09/13(후보)
    - 식사할거면 다른공간 대여 필요(조직위에서 결정)
        - 식사메뉴?

- Meeting Tower(deprecated)
    - Project-wise(주1회 이상)
        - 공지취합필요

- 640/607에 큰-쇼파(형태 변형 불가한 것) 필요한가요?

- 렉 MESH 철망(정리용, 후크걸수있는것)(구매요청 excel에 올려둠)

- 서버증설(not enough seed)
    - 큰모델 -> AWS?

- workstation 624 migration
    - 624 전기공사
    - network switch 추가 필요

- 640 자리 재배치

- 23-2학기(3선 방장 @cth127)
    - **박사생**이.. 하는게 지속성상으로 좋다...
    - 영수증처리, meeting주관
    - 경조사...?

**Comment by invigorator96** [comment]
미팅때 나온 이야기에 업데이트가 있습니다. 이번학기 서버실(624) 출입권한 승인받았습니다!
