### ISSUE TITLE
AIML@K Workshop - 2023 Fall 

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#133]
https://sites.google.com/view/aimlk-workshops

Tentative site is up. Any questions / suggestions, please contact the organizers

**Comment by d-h-lee** [comment]
Current slides PDF files are here: https://koreaoffice-my.sharepoint.com/:f:/g/personal/holy_korea_ac_kr/EkCTZnO7N8tOg8sZolQMfMQByCmEEU8SaMpq2d3wuGKQaw?e=ePlNz8
- Double check the fonts and images (low resolution will stand out in 유임순홀 screen)
- You may consider the other speakers' contents to customize your talk further (however, do not rely on it completely, as things can change last minute)
- If you need to update the files, you may do so in the link

**Comment by d-h-lee** [comment]
Instruction for the speakers:

- give a recital using your own machine, if you have not done it yet
- you will be able to use your machine on the workshop day, via Zoom "share screen"
- please arrive at the location 15 minutes before the beginning of your SECTION (not your talk) at the latest
- when you arrive, announce it to the workshop channel or to one of 운영위원 @choi430 @Ricepunchb 
- lastly, join the speakers' Zoom channel and wait for your turn

**Comment by cth127** [comment]
발표용 개인 노트북 필수 지참인지요? 아니면 홀에 화면 띄울 수 있는 공용 컴퓨터가 있을지요?

**Comment by d-h-lee** [comment]
공용 컴퓨터도 있습니다

**Comment by hojun-y** [comment]
@d-h-lee 
공용 컴퓨터에서 Keynote 사용 가능한가요?

**Comment by d-h-lee** [comment]
@hojun-y 아쉽지만 그게 안될것같군요. 유임순홀 컴퓨터가 윈도우입니다. 

혹시 키노트 쓰는 분들 @jungchanghae @wheresmadog 도와줄 수 있나요?

**Comment by jungchanghae** [comment]
키노트에 pptx로 내보낼 수 있는 기능이 있습니다.

**Comment by d-h-lee** [comment]
Thank you everyone for making this event happen! 

https://sites.google.com/view/aimlk-workshops/2023-fall website will be updated to reflect the photos

Also, the recorded sessions will be uploaded soon

**Comment by d-h-lee** [comment]
Recorded sessions are here: https://www.youtube.com/playlist?list=PLH93nND8kH5HSNEzdgF9ktKMsl7ac1cms
