### ISSUE TITLE
KSC 2023 공고

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#138]
공고가 떴습니다. 접수마감 10/13. 논문양식은 한글파일?! 

세부사항 검색해서 이 내용 대신에 넣어주세요.

**Comment by invigorator96** [comment]
KSC [홈페이지](https://www.kiise.or.kr/conference/main/getContent.do?CC=KSC&CS=2023&content_no=1871&PARENT_ID=010100)  링크 공유합니다

**Comment by JiHun-Lim** [comment]
논문 제출은 우선은 docx도 가능한 걸로 알고 있습니다.
docx로 제작된 pdf 버전의 예시를 공유해보려고 합니다.
[KSC_2021.pdf](https://github.com/AIML-K/bamboo-forest/files/12668592/KSC_2021.pdf)

**Comment by d-h-lee** [comment]
이것도 참조하면 좋습니다: https://github.com/AIML-K/bamboo-forest/issues/109

**Comment by d-h-lee** [comment]
이전에 @pinga999 가 알려준 (https://github.com/AIML-K/bamboo-forest/issues/109#issuecomment-1478983876) , 과거 KCC/KSC 논문들을 볼 수 있는 링크:  https://www.dbpia.co.kr/journal/publicationDetail?publicationId=PLCT00000760#none

컴퓨터 프로그래밍 요소가 없는 논문도 있군요;;; 
[UAE의 정세를 반영한 지대공 미사일의 고려사항.pdf](https://github.com/AIML-K/bamboo-forest/files/12679335/UAE.pdf)
