### ISSUE TITLE
고려대 수학과 대학원생 (+일부 학부생) 학회 @ 제주도, 2024년 1월 중순

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#139]
아직 확정공고가 나지는 않았지만, 미리 전파해도 되는 소식이라고 들어서 광고합니다

- 시기: 2024년 1월중/말 즈음 언제쯤
- 장소: 제주도 어딘가
- 대상: 고려대 수학과 대학원생 및 일부 학부생, 대략 20명-30명 전후
- 주최: 고려대 수학과
- 형태: 학회 (발표세션?)

학우들에게 연구발표를 할 수 있고, 장소 어드밴티지가 좀 있어보이는군요

세부 소식을 더 아는 분들은 자유롭게 업데이트 해주세요~

**Comment by d-h-lee** [comment]
2024년 1월에 학회가 열린다고 합니다 참가를 희망하시는 분은 링크에 들어가셔서 참가신청을 해주시기 바랍니다. 참가신청은 10월31일까지입니다.
https://form.jotform.com/232829170859467

@jungchanghae 알려줘서 고마워요~ 

어우.. 소소한 버그들이 있네요. 악용하지 말아주세요.
<img width="149" alt="image" src="https://github.com/AIML-K/bamboo-forest/assets/55645287/2ed3d8d6-bad8-40d6-acac-7704180b71cc">
<img width="235" alt="image" src="https://github.com/AIML-K/bamboo-forest/assets/55645287/4cdf8d57-c557-499b-b65d-a86b0642b46e">
 

발표 연습할 좋은 기회입니다:
<img width="675" alt="image" src="https://github.com/AIML-K/bamboo-forest/assets/55645287/5970a86a-dce6-46c6-93c5-589b5888396b">

**Comment by invigorator96** [comment]
학과 학술대회
2024년 1월 중순 제주도에서 2박 3일간, 분야 입문 수준의 소주제 강연, 대학원생들의 연구 소개, 학부생들의 주제발표, 토론 시간 등을 통해 수학과 학생들간의 학술 교류의 장을 마련할 예정입니다. 이 행사에 참석을 원하는 학생은 아래 내용을 기입하여 보내주세요. 30명 정도를 예상하고 있으며, 모두에게 숙박(2인 1실) 제공, 교통비는 개인부담, 발표자에게는 교통비 수준의 연사비 제공을 계획 중입니다. 신청 마감은 10월 31일입니다.

**Comment by d-h-lee** [comment]
이거 추진 안하게 될 것 같다는 소문이 있던데... 혹시 여러분들은 소식 들은 게 있나요?

**Comment by invigorator96** [comment]
참가자들에게 취소되었다고 공지가 전해졌습니다.

아래는 메일 전문입니다:

```
1월 제주도에서 열기로 했던 수학과 학회는 취소되었습니다. 외부 기금을 사용하는 방식에 대한 우려가 있어서 더 이상 추진하지 않기로 하였습니다.

학과 학회에 대해서는 일단 진리장학프로그램은 온라인 등으로 발표 기회를 마련해볼 것이고, 대학원생들의 경우 이학관 내 포스터
발표를 정기화하는 정도의 계획이 있습니다. 준비들도 나름 했었고 이런 행사에 대해 기대가 컸을텐데 모두에게 미안합니다.

학과장 김상집
```
