### ISSUE TITLE
11/1 3-4PM 서울대학교 백종호 박사님 방문 & 톡

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#145]
에폭시 과제 관련된 톡이 될 예정입니다. 에폭시랑 관련된 배경지식을 익히는데 좋은 기회가 될 것이라 참석 강추합니다.

**Comment by prism4304** [comment]
@d-h-lee 장소는 526인가요?

**Comment by d-h-lee** [comment]
넵 장소는 526이고, 연사분 도착이 조금 늦어지고있습니다.

**Comment by choi430** [comment]
해당 논문 링크
https://doi.org/10.1016/j.compositesb.2021.109058
