### ISSUE TITLE
11/8 ambers Reset & network resetting

### ISSUE THREAD

**Issue by jungchanghae** [AIML-K/bamboo-forest#146]
11월 8일에 ambers 초기화 및 네트워크를 중단할 예정입니다.

추가적으로 11월 8일부터 15일까지 네트워크 문제 해결을 위해서 중단될 수 있습니다.

8일 이전까지 ambers에 있는 데이터는 따로 백업을 해두시길 바랍니다.
또한 15일까지 네트워크가 끊길 수 있다는 상황을 인지하고 작업을 진행해주시길 바랍니다.

**Comment by pinga999** [comment]
NAS에 img 형태로 올라가있는 data들은 cleaning 대상이아니지요?

**Comment by jungchanghae** [comment]
> NAS에 img 형태로 올라가있는 data들은 cleaning 대상이아니지요?

네 NAS에 있는 data는 대상이 아닙니다.

**Comment by wheresmadog** [comment]
Close as done.
