### ISSUE TITLE
OneDrive 용량 제한 관련 

### ISSUE THREAD

**Issue by cth127** [AIML-K/bamboo-forest#150]
많은 분들이 메일을 받으셨겠지만, OneDrive 용량 정책이 다음과 같이 변경된다고 합니다.

![Screenshot_20231124_103916_NAVER WORKS.jpg](https://github.com/AIML-K/bamboo-forest/assets/44315098/81ccc9a6-5f3a-4476-85ee-9d6e3b1f9b16)

현재 aimlk-shared에만 100기가 가량의 영상 및 데이터 폴더가 있는 것으로 확인되고 있는 바, 대책이 필요합니다.

**Comment by invigorator96** [comment]
aimlk-shared 용량에서 상당부분은 영상들이라 nas에 백업하는 작업이 필요하겠습니다.

이 기회에 ftp서버를 운용하는 방법도...?

**Comment by d-h-lee** [comment]
여기 옮겼다 저기 옮겼다 정보인프라부가 구성원들에게 비용절감을 위한 추가노동을 강요하는군요.

연구실은 불필요한 추가노동을 최대한 피해야 연구를 진행할 시간이 나옵니다. 드롭박스 같은것을 구매해서 사용하겠습니다. 기존 원드라이브 파일을 포함하여, 안전한 보존이 필요한 파일 (타임캡슐이라든가...)들은 이곳으로 이동시키려고 합니다.

내부적으로 자주 쓰이는 대용량 파일 옮기는데는 내부FTP가 훨씬 낫습니다. 혹시 이런거 해보고 싶었다는 분들은 모여서 진행해주세요.

**Comment by cth127** [comment]
@d-h-lee 정보인프라부에서 예고한 용량 조정 대상 계정 로그인 차단이 1월 2일로 예고된 바, 드롭박스 이주를 오는 주 안에 해결할 필요가 있습니다.

**Comment by d-h-lee** [comment]
이주한 주소들은 https://github.com/AIML-K/readme/issues/59 여기에 있습니다
