### ISSUE TITLE
KSC 2023 참가비 지원 프로그램

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#152]
<img width="952" alt="image" src="https://github.com/AIML-K/bamboo-forest/assets/55645287/bb0d9d21-a702-44d3-9f88-3c387e6dda3b">

**Comment by pinga999** [comment]
조금 전화통화를 통해 상세한 사항들을 알아보았는데,

해당 지원을 받기위한조건이 아래와 같습니다
- 한국정보과학회 회원(웹회원 제외, 최소금액 50000)
- 이번에 논문게재를 한 저자
- 소속기관의 소재지가 부산이아니다
- 연구비카드가아닌 개인카드로 결제

이중 2.3.4.의 경우를 모두 충족하는사람들이일부 존재합니다만,
1.에 비용이 드는데에비해, 확정적으로 지원을 받을수 있는것은 아니라고합니다.

참고바랍니다

**Comment by invigorator96** [comment]
어차피 회원비+학회등록비(회원가) 와 학회등록비(비회원) 이 차이가 거의 안나서 전원 회원비 내고 가입해도 딱히 문제 없습니다

**Comment by pinga999** [comment]
> 어차피 회원비+학회등록비(회원가) 와 학회등록비(비회원) 이 차이가 거의 안나서 전원 회원비 내고 가입해도 딱히 문제 없습니다

하필 문제라면... 논문저자는 어제까지 등록이었어서 이걸 몰랐달까요...?

**Comment by prism4304** [comment]
@pinga999 접수마감이 11.30까지 따로 존재하는데 저자들 사전등록기간인 11.27일과는 별개로 신청될 수도 있을 것 같은데 확인 한 번 해보는 것도 좋아보입니다.

**Comment by pinga999** [comment]
> @pinga999 접수마감이 11.30까지 따로 존재하는데 저자들 사전등록기간인 11.27일과는 별개로 신청될 수도 있을 것 같으니 확인 한 번 해보는 것도 좋아보입니다.

전화로 처리해서 저랑 김양기학생은 회원가입후 등록처리했습니다
