### ISSUE TITLE
2024 봄학기 워크샵 일정 결의

### ISSUE THREAD

**Issue by cth127** [AIML-K/bamboo-forest#160]
냉무

**Comment by pinga999** [comment]
- 잠정적 1순위 일자 : 24/03/08

**Comment by pinga999** [comment]
Things to do
- [ ] Poster
- [ ] Homepage
- [ ] Place Rent
- [ ] 추진위( 전대 추진위 제외 (if possible!) -> OB 1ㅅ, 뉴비 1ㅅ)

**Comment by invigorator96** [comment]
> 추진위( 전대 추진위 제외 (if possible!) -> OB 1ㅅ, 뉴비 1ㅅ) (0207 사다리 타기)
@2nazero @cth127 당첨
