### ISSUE TITLE
2024 봄학기 부트캠프 덧붙이기

### ISSUE THREAD

**Issue by cth127** [AIML-K/bamboo-forest#161]
어제 타운홀에서 별도의 부트캠프를 진행하려면 지금 해야한다는 의견을 받았습니다. (@invigorator96)

교수님께 확인한 결과, `#bootcamp-2024-1` 채널에서 on-demand로 진행중이지만, 뭔가 신입생들한테 가르쳐줘야될 것이 있다면 따로 오프 세션으로도 좋을 것 같다는 의견을 받았습니다. (@d-h-lee)

이에 부트캠프 덧붙이기 세션을 모집해볼까 합니다. 다음과 같은 내용 (이외에도 필요하다고 생각되는 내용이 있다면 추가해주세요)에 대해 간단한 실습 세션을 진행해주실 분을 모집합니다.

- 기초 Linux 및 SSH 활용법
- Git 활용법
- Docker 활용법
- IDE (VS Code, PyCharm), 디버거 활용법

@AIML-K/grads 댓글 통해 많은 자원 바랍니다 (자원이 부족할 경우 모시러 가겠습니다^^)

**Comment by 2nazero** [comment]
하게 된다면 저는 2번 git 하겠습니다.

**Comment by pinga999** [comment]
IDE 디버거 잔행하겠습니다!

**Comment by choi430** [comment]
'기초 Linux 및 SSH 활용법' 맡겠습니다.

**Comment by hamgcho** [comment]
Docker 활용법 맡겠습니다

**Comment by jongwon-han** [comment]
안녕하세요! 이동헌 교수님께는 따로 말씀드렸는데 가능하다면 저희 연구실 학생 3명도 참가가 가능할까요?
조교 학생들이 이번 학기 수업에서 활용할 내용들이라 만약 저희도 참석이 가능하다면 정말 좋은 기회가 될듯합니다.

- 석사(3학기)/박사(신입)/박사(4학기)
- 모두 Linux 및 SSH는 익숙하지만 나머지 내용들은 처음 접하는 상태입니다.
- 파이썬은 모두 익숙하지만 IDE 계열 편집기 및 디버거 활용은 잘 모릅니다.

**Comment by cth127** [comment]
@jongwon-han 안녕하세요~ 렉쳐러들 모두 괜찮다고 답변 받았습니다. linux/ssh 세션 제외한 시간표는 다음과 같으며, 개인 노트북 지참하여 640으로 오시면 될 것 같습니다. ^^

 2월 27일 화요일 14-15시: Git (나영 씨)
 2월 29일 목요일 13-15시: IDE/디버거 (한영 씨)
 3월 4일 월요일 12-13시: Docker (근석 씨)

**Comment by jongwon-han** [comment]
감사합니다! 학생들에게도 전달해두도록 하겠습니다:)

**Comment by 2nazero** [comment]
혹시 640에 렉쳐러 다 포함해서 7명이 노트북 가지고 다 앉을 자리가 있을까요?

**Comment by cth127** [comment]
@2nazero 가운데 회의테이블 정도면 충분하지 않을까요? 모서리에 둘씩 앉으면..
