### ISSUE TITLE
2024년 봄 워크샵 발표 제목 및 일정 수합

### ISSUE THREAD

**Issue by cth127** [AIML-K/bamboo-forest#162]
@AIML-K/grads 2024년 봄 워크샵 발표 제목 및 금요일 일정을 수합하려 합니다.

발표자 분들은 **2월 23일 (이번주 금요일) 오후 열두시 전까지 (i) 워크샵 발표 제목과 (ii) 금요일 수업/조교/기타 워크샵 참여가 어려운 시간**을 댓글로 남겨주세요~

**Comment by 2nazero** [comment]
매주 금요일 9-12시 조교활동으로 인해 불가
8일 금요일 18시-21시 조교교육으로 인해 불가

**Comment by cth127** [comment]
제목: Pre-trained Language Models Return Distinguishable Probability Distributions to Unfaithfully Hallucinated Texts
시간: 3월 15일, 22일 학회 참여로 워크샵 참여 불가능

**Comment by invigorator96** [comment]
Seismic waveform synthesis with diffusion model

또는

Mildpruning: structural pruning by Bypassing algorithm

으로 하겠습니다.

발표시간은 제약 없습니다

**Comment by hamgcho** [comment]
제목 : How should I split my Dataset?
발표시간 제약 : 없음

**Comment by prism4304** [comment]
제목 : What is PINN? 또는 Epoxy : Out of Detection for Improving Prediction Accuracy 로 하겠습니다.
모든 시간 참여 가능합니다.

**Comment by pinga999** [comment]
제목 : AI on Finance Domain

시간제약 : 금 12시부터 15시 조교활동이있습니다

**Comment by choi430** [comment]
제목: Chemical Property Prediction on Epoxy Adhesives (수정 가능성 있습니다)
시간 제약: 없음

**Comment by jungchanghae** [comment]
제목 : 나라지식정보 인턴(가제목)

시간제약 : 금 12시부터 15시 조교활동

**Comment by jongwon-han** [comment]
발표제목 전달이 늦어서 죄송합니다🥲
저희는 모든 시간대에 발표 가능합니다.

서보성 (석사과정)
Deep Learning-based Estimation of Hypocentral Distance and Back Azimuth for Earthquake Location
한종원 (박사과정)
Comprehensive Earthquake Parameter Determination using the AI Techniques: Case Study on the Southeastern Korean Peninsula

**Comment by 2nazero** [comment]
| 시간       | 발표자  | 주제                                                     |
|------------|---------|----------------------------------------------------------|
| 10:00-10:30 | 정창해   | 나라지식정보 인턴(가제목)                                |
| 10:30-11:00 | 조근석   | How should I split my Dataset?                           |
| 11:00-11:30 | 최완선   | Chemical Property Prediction on Epoxy Adhesives          |
| 11:30-12:00 | 서보성   | Deep Learning-based Estimation of Hypocentral Distance and Back Azimuth for Earthquake Location |
| 12:00-12:30 | 한종원   | Comprehensive Earthquake Parameter Determination using the AI Techniques: Case Study on the Southeastern Korean Peninsula |
| 12:30-13:00 | 이나영   | text2image                                         |
| 13:00-14:00 | **점심시간/휴식** |                                                          |
| 14:00-14:30 | 정재헌   | Seismic waveform synthesis with diffusion model (변경 간ㅇ)        |
| 14:30-15:00 | 하정운   | What is PINN?                                            |
| 15:00-15:30 | 차태훈   | Pre-trained Language Models Return Distinguishable Probability Distributions to Unfaithfully Hallucinated Texts |
| 15:30-16:00 | 김한영   | AI on Finance Domain                                     |

**Comment by 2nazero** [comment]
| 시간       | 발표자  | 주제                                                     |
|------------|---------|----------------------------------------------------------|
| 11:00-11:30 | 최완선   | Chemical Property Prediction on Epoxy Adhesives          |
| 11:30-12:00 | 정창해   | 나라지식정보 인턴 (가제목)                                |
| 12:00-12:30 | 조근석   | How should I split my Dataset?
| 12:30-13:00 | 이나영   | text2image (변경 예정)                        |
| 13:00-14:00 | **점심시간/휴식** |
| 14:00-14:30 | 서보성   | Deep Learning-based Estimation of Hypocentral Distance and Back Azimuth for Earthquake Location |
| 14:30-15:00 | 한종원   | Comprehensive Earthquake Parameter Determination using the AI Techniques: Case Study on the Southeastern Korean Peninsula |                                       |                    |
| 15:00-15:30 | 정재헌   | Seismic waveform synthesis with diffusion model (변경 가능)        |
| 15:30-16:00 | 하정운   | What is PINN?                                            |
| 16:00-16:30 | 차태훈   | Pre-trained Language Models Return Distinguishable Probability Distributions to Unfaithfully Hallucinated Texts |
| 16:30-17:00 | 김한영   | AI on Finance Domain                                     |


2차 가안 업로드합니다. 10시-16시보단 11시-17시가 더 사람이 많이 올 것 같아서 일정을 살짝 조율하였습니다.

아직 가제목 및 변경 예정 가능인 분들 최종 발표 제목을 제게 월요일 (3/4) 23:59까지 댓글로 알려주세요

**Comment by jungchanghae** [comment]
제목 : What did I do on the Nara-Tour?

**Comment by 2nazero** [comment]
@jongwon-han 안녕하세요! 이번에 워크샵 편성 위원인 MDS 이나영이라고 합니다! 다름이 아니라 포스터를 만드는 중인데 발표자분들 랩실 이름 알려주실 수 있을까요? 아니면 어떤 식으로 표기해주셨으면 좋겠다 등의 관련 정보 알려주시면 감사하겠습니다!

**Comment by jongwon-han** [comment]
안녕하세요, 워크숍 준비 감사드립니다. 간단하게 '지진학 연구실' 정도로 부탁드립니다.

**Comment by 2nazero** [comment]
🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
🚨오늘(3/4) 23:59에 워크샵 발표 제목 수합 마감입니다!!! 오늘까지 제목 변경하시거나 확정지으실 분들은 여기에 코멘트로 남겨주세요!!!!!!🚨
 🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

**Comment by 2nazero** [comment]
이 이후로 변경하실 분은 밑에 코멘트 더 추가해서 남겨주세요!
