### ISSUE TITLE
2024-1 TownHall 시간표 취합

### ISSUE THREAD

**Issue by pinga999** [AIML-K/bamboo-forest#164]
2024-1 TownHall 시간표 취합

본인이 `불가능한` 시간을 요일별로 적어주세요

`기본 포맷`

월 :
화 :
수 :
목 :
금 :

**Comment by jungchanghae** [comment]
월 : 15:00~16:15
화 : 9:00~10:15
수 : 15:00~16:15
목 : 9:00~10:15
금 : 12:00~14:45

**Comment by invigorator96** [comment]
월 :00:00~09:30, 18:30~24:00
화 :00:00~09:30, 18:30~24:00
수 :00:00~09:30, 18:30~24:00
목 :00:00~09:30, 18:30~24:00
금 :00:00~09:30, 18:30~24:00

**Comment by 2nazero** [comment]
월 : 13:00 - 16:30
화 :  10:30-12:00
수 : 13:00 - 16:30
목 :10:30-12:00
금 :9:00 -12:00

**Comment by choi430** [comment]
월 :
화 : 14:00 - 17:00
수 :
목 : 14:00 - 17:00
금 :

(개강 후 첫 주) 수강 신청 변경이 없다면 이대로입니다.

**Comment by Ricepunchb** [comment]
월 : 0900 - 1030, 1500 - 1630
화 : 0900 - 1200, 1500 - 1800
수 : 0900 - 1030, 1500 - 1630
목 : 0900 - 1300
금 :

**Comment by cth127** [comment]
월
화
수
목
금 15:00 -

**Comment by sjki928** [comment]
월 : 15:00 - 16:15
화 : 10:30 - 11:45, 15:00 - 18:00
수 : 15:00 - 16:15
목 : 10:30 - 11:45
금 :

**Comment by kyungheee** [comment]
월 : 9:00-10:30, 13:30-16:30
화 : 10:30-12:00
수 : 9:00-10:30, 13:30-16:30
목 : 10:30-12:00
금 : 9:00-10:30

**Comment by Yeazzing** [comment]
월 : 8:30 - 12:30, 13:30 - 14:45
화 : 10:30 - 11:45, 13:30 - 16:15
수 : 8:30 - 12:30, 13:30 - 14:45
목 : 10:30 - 11:45, 13:30 - 17:30
금 : 8:30 - 12:30, 13:30 - 17:30

**Comment by pinga999** [comment]
월 17:00~
수 17:00~

일단 추려졌습니다!

**Comment by pinga999** [comment]
- TownHall Time Fix!
    - Wed 17:00~ ASB 526
