### ISSUE TITLE
워크샵 다과 사러 갈 사람들 구함

### ISSUE THREAD

**Issue by cth127** [AIML-K/bamboo-forest#167]
안녕하세요? 워크샵 날 먹을 다과 사러 갈 파티를 모집합니다.

일자는 3월 7일 목요일 오후중 생각하고 있고, 퇴근시간 피하려면 4시쯤 출발하는 게 어떨까 합니다.

같이 장 보러 가실 분들은 따봉 표시 남겨주세요~

PS. @d-h-lee 다과 살 때 연구비 카드 이용하면 될지요?

PS2. @choi430 기억하기로 당일날 유임순홀 앞에 테이블을 비치해뒀던 거 같은데, 혹시 어디서 가져올 수 있을까요?

**Comment by choi430** [comment]
@cth127 유임순홀 내부 입구와 가까운 곳 구석에 놓여있었던 테이블입니다. 총 4개인가 있었던것 같습니다.

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________
From: cth127 ***@***.***>
Sent: Tuesday, March 5, 2024 2:17:44 PM
To: AIML-K/bamboo-forest ***@***.***>
Cc: choi430 ***@***.***>; Mention ***@***.***>
Subject: [AIML-K/bamboo-forest] 워크샵 다과 사러 갈 사람들 구함 (Issue #167)


안녕하세요? 워크샵 날 먹을 다과 사러 갈 파티를 모집합니다.

일자는 3월 7일 목요일 오후중 생각하고 있고, 퇴근시간 피하려면 4시쯤 출발하는 게 어떨까 합니다.

같이 장 보러 가실 분들은 따봉 표시 남겨주세요~

PS. @d-h-lee<https://github.com/d-h-lee> 다과 살 때 연구비 카드 이용하면 될지요?

PS2. @choi430<https://github.com/choi430> 기억하기로 당일날 유임순홀 앞에 테이블을 비치해뒀던 거 같은데, 혹시 어디서 가져올 수 있을까요?

**Comment by 2nazero** [comment]
@cth127 한종원님께서 "유임순홀은 음식불 반입불가이니 참석자 분들께 전달 부탁드립니다!" 라는 연락이 왔습니다. 참고 부탁드립니다.

**Comment by 2nazero** [comment]
유임순홀 내부에 음료는 불가능하고 물까지 허용한다고 합니다. 참고 부탁드리겠습니다!!

**Comment by cth127** [comment]
@invigorator96 @prism4304 @2nazero @jungchanghae @pinga999 @Ricepunchb 모두 고맙습니다!
