### ISSUE TITLE
워크샵 줌 송출 이슈

### ISSUE THREAD

**Issue by 2nazero** [AIML-K/bamboo-forest#169]
내일 진행될 워크샵의 발표가 Zoom을 통해 외부에 송출될 예정입니다. 이와 관련하여 어떠한 우려사항이 있으신 분들은 댓글로 의견을 남겨주시길 바랍니다.

또한, 발표 송출 범위에 대해서도 여러분의 의견을 구하고자 합니다. 다음 중 어느 범위까지 송출을 허용하시는 것이 좋다고 생각하시는지 공유해 주시기 바랍니다.
1. 아예 줌 공유 자체를 하지 말 것
2. 지환과 및 수학과 내부에서만
3. 고려대학교 학생 전체에게만
4. 고려대학교 외부까지도 포함하여
5. 기타 (송출을 허용하되, 본인 발표할 때만 잠시 공유를 정지시키는 등의 방법)

여러분의 의견을 기다리겠습니다. 안전하고 효과적인 워크샵 진행을 위해 여러분의 소중한 의견이 필요합니다.

‼️그리고 당연한 것이지만 발표자마다 발표 이전에 줌 송출에 대해 의사를 여쭤볼 것입니다!

ps. 이미 수학과 전체 이메일로는 줌 주소도 같이 포함되어 전송이 된 상태입니다. 만약 1번으로 하게 된다면 수학과 행정실측에 재공지를 요청드려야 될 것 같습니다.

@AIML-K/grads @jongwon-han

**Comment by invigorator96** [comment]
워크샵에서 다루는 발표 중에는 unpublished work들이 있어서 반대이긴 합니다. 

혹시 온라인 송출을 허용할 거라면 온라인 접속한 청중의 질문도 받아 줄 것인지도 생각해 볼 문제라고 생각합니다.

**Comment by 2nazero** [comment]
먼저 의견 감사드립니다.

넵 저도 이 상황에 대해서 인지하고 있고, 그래서 의견을 여쭌 것입니다.

혹시 1번이나 5번 중 어떤 방법이 나을지 의견 있으실까요?

온라인 접속한 청중의 질문도 받아 주는 것 관련해서도 의견 있으시면 알려주시면 반영하도록 하겠습니다.

**Comment by invigorator96** [comment]
저는 1번에 한 표, 어쩌면 2번 정도는 괜찮겠다 싶은 정도입니다.

**Comment by cth127** [comment]
1번은 물리적으로 안 하면 그만이긴 한데... 2, 3, 4번을 나눠서 받을 수 있는 방법이 있나요?

개인적인 생각으로는 우리끼리 뭐 했다고 얘기하고 끝나는 자리가 아니라 애초에 외부인도 올 수 있도록 홍보까지 한 자리인만큼, 큰 문제 없다고 생각합니다.

**Comment by cth127** [comment]
논의 결과 일단 줌 송출은 기본으로 하되, 줌 송출을 동의하지 않는 발표자의 세션의 경우 일시 중단하는 방향으로 하겠습니다.
