### ISSUE TITLE
Git (branching) guide 제작

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#17]
@cth127 가 첫삽을 들어준 것을 기반으로 만들어 보겠습니다

**Comment by d-h-lee** [comment]
@prism4304  튜토리얼 취합할때 반영해주세요~

**Comment by prism4304** [comment]
https://github.com/AIML-K/for_education의 readme.md, Git(hub) 부분에 간단하게 설명이 되어 있습니다.

**Comment by d-h-lee** [comment]
> https://github.com/AIML-K/for_education readme.md, Git(hub) 부분에 간단하게 설명이 되어 있습니다.

설명이 되어있으니 이 이슈는 닫겠습니다. git branching 등에 대한 세션이 필요한 사람이 있으면 이 이슈를 다시 부활시켜주세요.
