### ISSUE TITLE
2024 여름방학 기간동안 오승상교수님 연구실과 joint journal club

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#178]
교수님들 선에서 이야기가 오가는 단계입니다. 그러니 구체적인 방향 및 제안을 할 좋은 기회입니다.

현재 논의되는 안은 다음과 같습니다:

- 여름방학 기간동안
- 매주 2일 (목요일,금요일 - 오승상교수님 스케쥴 constraint)
- 학생들이 논문을 읽고 발표
- 양 연구실 학생들이 방청객으로 참석하여 피드백

**Comment by d-h-lee** [comment]
금요일 오후2시에 정기적으로, 7/12부터 시작하는 것으로 이야기가 되었습니다~

**Comment by d-h-lee** [comment]
7/12 

- 정상혁 TD3
- 차태훈 SentenceLDA https://aclanthology.org/2024.eacl-long.31.pdf

7/19

- 최선묵 SincNet filter
- 정재헌 Bypassing https://ieeexplore.ieee.org/document/10569069

**Comment by pinga999** [comment]
@d-h-lee 이 이슈 닫아도될까요?

**Comment by d-h-lee** [comment]
넵!
