### ISSUE TITLE
5/31 4-5PM 수학과 세미나: Formation-Controlled Dimensionality Reduction

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#179]
1. 일시 : 2024년 05월 31일(금) 오후 4시~5시

2. 장소 : 아산이학관 526호(권택연 세미나실)

3. 연사 : 정윤모 교수님 (성균관대학교)

4. 제목 : Formation-Controlled Dimensionality Reduction

5. 초록 : Dimensionality reduction represents the process of generating a low dimensional representation of high dimensional data.  In this talk, I explain what dimensionality reduction is and shortly mention formation control. After that, I will introduce a nonlinear dynamical system designed for dimensionality reduction. I briefly discuss mathematical properties of the model and demonstrate numerical experiments on both synthetic and real datasets.

**Comment by d-h-lee** [comment]
아.. 이 톡 가고 싶었으나 너무 바빠서 못갔습니다. @AIML-K/grads 혹시 참석한 분..?

**Comment by invigorator96** [comment]
저는 일정이 있어 참석 못했습니다 ㅜㅜ

**Comment by cth127** [comment]
참석은 했었으나 어려워 잘 이해하지 못했습니다🥲
