### ISSUE TITLE
여름방학 회의실 예약 - 6/14오전10시까지 백진경선생님께 회신필요

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#181]
시간 장소 정해서 @d-h-lee 콜아웃 해주세요~

-----

2024-여름방학 세미나실 이용 관련하여 

세미나실을 고정으로 사용하실 분은 2024.06.14.(금) 오전 10시까지 회신 부탁드립니다. 

1. 사용기간: 2024.06.22.(토)-2024.09.01.(일)

2. 사용공간: 아산이학관 516호, 524호, 525호, 526호, 641호

**Comment by d-h-lee** [comment]
저널클럽이랑 미팅타워..?

**Comment by pinga999** [comment]
저널클럽 진행시간은 생각해두신게 있으신가요?

**Comment by d-h-lee** [comment]
아뇨 다들 되는시간이 언제인지 이야기해서 정하도록 하죠.

금요일 오후2-4시는 오승상교수님쪽이랑 같이 하는 것이니 그때는 피하구요
