### ISSUE TITLE
8/30 오후3시 - 1시간짜리 발표 슬롯 하나가 빕니다.

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#189]
#187 과 함께 발표하는 기회가 있습니다. 인공지능에 관심있는 수학과 학부 및 대학원생들이 주 방청객입니다.

박사과정 학생이 선순위입니다. 그러니 지원자가 8/18 일요일까지도 없다면, @prism4304 @pinga999 중에서 정하도록 하겠습니다.

#187 처럼 다른 사람의 유명한 논문을 발표하는것도 가능합니다만, 본인이 연구한 내용이 담긴 논문 또는 연구하고 있는 내용과 관련성이 큰 논문을 발표하는 것을 추천합니다. 

PS. 9/6 AIML@K 세미나도 있습니다. 이쪽도 발표세션들이 많이 있으니, @AIML-K/grads 모두 각자 자신의 연구에 대한 발표(적어도 20분정도)를 준비해주세요.

**Comment by prism4304** [comment]
@d-h-lee 제가 하겠습니다.

**Comment by d-h-lee** [comment]
@prism4304 알겠습니다. 준비를 잘 진행해주길 바라고, 8/19이나 20일에 업데이트 부탁합니다

**Comment by prism4304** [comment]
@d-h-lee 개인사정이 있어 답변이 늦은 점 죄송합니다.
PPSDGAN https://ieeexplore.ieee.org/abstract/document/10609442 으로 발표하겠습니다.

**Comment by d-h-lee** [comment]
@prism4304 발표자료를 전에 했던게 있을텐데, 피드백으로 개량할만한 점들을 찾았을겁니다 + 추가연구 진행이 된 게 있을것같습니다. 

반영해서 발표자료 초안을 26일 월요일 저녁까지 보내주세요~

초안
