### ISSUE TITLE
2024년 가을 워크샵

### ISSUE THREAD

**Issue by jungchanghae** [AIML-K/bamboo-forest#190]
일정 : 9월 6일 11시 ~ 17시
발표 인원 : 10명 (aimlk 7명 + 오승상 교수님 연구실 3명)
장소 : 아산이학관 6층 원형 강의실? -> 아직 시간표 확정이 안돼서 30일 오후에 대관 예정
발표 시간 : 30분

- [x] 포스터 제작
- [x] [홈페이지](https://aiml-k.github.io/event/24-03-08-aimlk_spring_workshop_2024/) 수정

**Comment by jungchanghae** [comment]
@AIML-K/grads 2024 가을 워크숍 발표 제목을 미리 받아두려고 합니다. 

발표 제목을 Comment로 남겨주세요! (가제목을 남겨주셔도 됩니다.)
그리고 혹시 발표 참여가 힘든 시간대가 있다면 추가로 알려주세요!

**Comment by kyungheee** [comment]
Optimizing Regression Models with VAE: A Comparative Study of Bayesian Approaches (가제목)

**Comment by JeongYejin1226** [comment]
Is Your Back in Good Shape?

**Comment by Yeazzing** [comment]
@AIML-K/grads 워크숍 발표 제목 9/4 수요일까지 남겨주시기 바랍니다!

**Comment by jungchanghae** [comment]
How to use Chatbots in lectures

**Comment by d-h-lee** [comment]
- 노경희 (Kyunghee Roh): Optimizing Regression Models with VAE
- 이예진 (Yeajin Lee): Diagnosing Spine Conditions Model for RSNA 2024 Kaggle Contest
- 정예진 (Yejin Jeong): Is Your Back in Good Shape?
- 정창해 (Chang-Hae Jung): How to Use Chatbots in Lectures
- 최완선 (Wanshan Cui): Identifying Trading Signals in High-Frequency Data through Anomaly Detection

- 이기환 (Kihwan Lee): Multimodal Representation Learning
- 이승은 (Seungeun Lee): Voice Spoofing Detection & Speaker Verification
- 최찬혁 (Chanhyuk Choi): Stock Predict with Wavelet Transform

**Comment by jungchanghae** [comment]
제목들은 모두 포스터에 올려서 홈페이지와 메일로 전달된 상황이라 이 issue는 닫겠습니다.
