### ISSUE TITLE
2024-2 townhall 시간조율

### ISSUE THREAD

**Issue by pinga999** [AIML-K/bamboo-forest#191]
댓글에 본인이 참여가 **불가능한** 시간을 적어주세요!
가급적이면 평일 9-18시 사이로 잡으려합니다

- 월 : 오전
- 화 : 전체
- 수 : 오전
- 목 : 전체
- 금 : 12-15시

**Comment by 2nazero** [comment]
- 월 : _
- 화 : 10:30-12/ 13:30-15
- 수 :_
- 목 : 10:30-12/ 13:30-15
- 금 : _

* 오전 7-10시/ 늦은저녁 (7시 이후) 매일 안 됨

**Comment by invigorator96** [comment]
- 월: 오전 9:00~ 9:30
- 화: 오전 9:00~ 9:30
- 수: 오전 9:00~ 9:30
- 목: 오전 9:00~ 9:30
- 금: 오전 9:00~ 9:30

**Comment by cth127** [comment]
따로 없음

**Comment by jungchanghae** [comment]
따로 없습니다.

**Comment by Yeazzing** [comment]
- 목 : 18:00 이후 
(수강신청에 따라 추가되는 시간이 생길 수 있습니다)

**Comment by JeongYejin1226** [comment]
- 화 : 9:00 ~ 15:00
- 목 : 9:00 ~ 15:00

**Comment by choi430** [comment]
- 금: 9:00 - 13:00

**Comment by Ricepunchb** [comment]
**2학기 인턴으로 인한 참여불가**

**Comment by sjki928** [comment]
2학기 인턴 근무로 참여불가합니다.

**Comment by pinga999** [comment]
![image](https://github.com/user-attachments/assets/af9c1ea0-86bd-4a85-8613-1fc420f19154)

빨간 부분이 현재 불가능한 시간표들이고, 여러사람들의 식사시간까지 고려한다치면 월,수 14시이후 슬롯들이 비어있는 상황입니다. 참고부탁드립니다!

**Comment by kyungheee** [comment]
월요일 : 2:00-5:00
화요일 : 1:30-3:00
수요일 : 2:00-5:00
목요일 : 1:30-3:00
금요일 : 2:00-6:00

**Comment by pinga999** [comment]
수요일 17시에 진행하는걸로 되었습니다!
