### ISSUE TITLE
워크숍 다과 준비

### ISSUE THREAD

**Issue by jungchanghae** [AIML-K/bamboo-forest#192]
워크샵 날 먹을 다과 사러 갈 사람 구합니다.

9월 5일 목요일 3시에 연구실에서 출발로 생각하고 있습니다.

같이 장 보러 가실 분들은 따봉 표시 남겨주세요 !

원하시는 것이 있을 경우 코멘트로 남겨주세요

**Comment by pinga999** [comment]
![2554729746.jpg](https://github.com/user-attachments/assets/14aae770-db27-4d63-93b7-e29f29575104)

**Comment by JeongYejin1226** [comment]
![image](https://github.com/user-attachments/assets/6d94d3e4-ab87-468d-b1bd-394ac62d5f48)
![image](https://github.com/user-attachments/assets/db772851-b66a-4be3-ab98-fcf0b8ca30ac)

**Comment by cth127** [comment]
비가 옵니다..?

**Comment by cth127** [comment]
홈플러스 익스프레스나 비마트같은 걸로 배달시키는 것도 방법일 거 같아요

**Comment by pinga999** [comment]
익스프레스랑 비마트 둘다 만나서결제가 안되는문제가있네요....

**Comment by cth127** [comment]
전에 법카로 홈플 익스프레스 시켰던 거 같은데... 만카결 하는 이유가 영수증 떼는게 어려워서였지요 아마? 비마트는 지류영수증을 줄런지 모르겠네요

**Comment by cth127** [comment]
아 생각해보니 만카결 한 게 가게 상호명이 안 나와서였군요. 비마트가 상호면 괜찮...을지도..?

**Comment by jungchanghae** [comment]
비마트는 카드로 결제하려면 카드 비밀번호가 필요하고,,,
홈플러스 익스프레스는 제일 빠른 배송시간이 내일 11~15시라고하네요 ㅠ 
이마트로 가는게 나을 것 같습니다,,,

**Comment by pinga999** [comment]
구매 완료! 다들 고생하셨습니다!
