### ISSUE TITLE
4/28~4/29: 2022 KMS (Korean Math Society) Spring Meeting

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#21]
https://www.kms.or.kr/md_meet/main.html?period=78&idx=5
<img width="552" alt="image" src="https://user-images.githubusercontent.com/55645287/158927088-25323fbd-1f1a-4896-b89c-3291a9c967c3.png">

절대 관련 없지 않습니다. 머신러닝 열어보면 다 수학이에요.

관심있을법한 주제들이 있으면 자유롭게 코멘트 달아주세요. @AIML-K/grads -- highly recommended.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/55645287/158927406-51b75439-de1e-4ef0-8865-d26966c22ad0.png">
<img width="727" alt="image" src="https://user-images.githubusercontent.com/55645287/158927430-327e600f-6e06-493b-8f60-f8a022791bca.png">

**Comment by invigorator96** [comment]
[여기](https://www.kms.or.kr/conference/abstract/search.html)

에서 발표 예정인 Abstract 들 확인할 수 있습니다~

**Comment by hamgcho** [comment]
저는 응용대수 및 최적화이론 (SS-11)이 재미있을 것 같습니다

**Comment by cth127** [comment]
저는 SS 07, 10, 11 / FS 02, 03에 눈길이 가네요

**Comment by invigorator96** [comment]
Note) 매 학기 대한수학회의 경우 BK21 사업단에서 등록비를 지원해 줍니다. 수학과 소속의 참여대학원생이면 신청할 수 있고, 보통 2주쯤 전에 공지해서 명단 모으고 대한수학회 측에 직접 결제하는 형식이에요. 등록 일정과는 무관한 듯 합니다(등록일정이 지난 뒤에도 등록해봤습니다...발표자일 때요...)

참고로 대한수학회 회원으로서의 회비와는 무관하니 대한수학회 회원으로 등록하려면 사비(...)로 등록하거나 다른 수단을 동원해야 합니다.

**Comment by d-h-lee** [comment]
등록비 관해서는 #22 조직팀에서 좀 더 살펴봐주세요

**Comment by hamgcho** [comment]
네 알겠습니다.

**Comment by invigorator96** [comment]
closing outdated events.
