### ISSUE TITLE
2022 KMS Spring Meeting 참석 이벤트 조직

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#22]
4/28-29. Two-day long conference.

Quite a lot of lab members will attend this (I really hope so). See #21. 

We need a couple of volunteers to make this more fun. For example:
- [ ] set up local sessions (reserve room. e.g.) to see the event together (this will help discussion among us as well)
- [ ] get some finger food for us to chew on (more fun!)
- [ ] anything else? please suggest.

**Comment by hamgcho** [comment]
지원하겠습니다~!

**Comment by hamgcho** [comment]
> 안녕하세요.
BK 수학교육연구팀의 유재인입니다.
> 4월4일까지 참여대학원생의 지원서 및 기타 서류 제출, 자격을 검토하고 10일 이후 확정이 된 후 
학회지원을 공지하고 진행할 예정입니다.

위의 내용은 수학과 BK21 사업단을 담당하는 유재인님에게 문의한 결과입니다.

요약하자면, BK21 참여대학원생에 한해서 4월 둘째주에 학회지원 관련하여 공지를 주신다고 합니다.
제가 BK21 참여대학원생에 선발되지 않을 가능성도 있어 제가 선발되지 않는다면
연구실 내에 참여대학원생으로 선발되신 분이 관련하여 알아봐야 할 듯 합니다.

**Comment by hamgcho** [comment]
4월 29일 대한 수학회 발표회 일정이 끝나면 조촐하게라도 연구실 파티를 하면 좋을 것 같은데 다들 어떠신가요?

**Comment by hamgcho** [comment]
> 둘째주 공지받는 대로 연구발표회 등록비 지원을 진행하도록 하겠습니다

둘째 주가 지났음에도 불구하고 연락이 없어 유재인 선생님께 문의 드렸고, 문의 결과 조만간 공지해주신다고 합니다.

**Comment by hamgcho** [comment]
관련 메일을 곧 바로 보내주셨습니다.
4월 20일까지의 제출 기한이 있다고 합니다.

![image](https://user-images.githubusercontent.com/68200616/163804947-b1ba9cae-e14d-422f-badd-317825aacf0c.png)


그런데 두 가지 확실하지 않은 점이 있습니다.
- 참여대학원생 한 명만 신청 후, 함께 시청하는 것은 문제가 되는지,
- 문제가 된다면, **참여 대학원생이 아닌 인원에 대한 지원**의 방법
입니다.

후자는 문의 해 보도록 하겠습니다.

**Comment by wy-july** [comment]
대한수학회 측에서 세부적인 일정이 나와서, 수요조사를 통해 시간표 배정 및 강의실 대여를 하였습니다.
<figure class="md-table-fig" cid="n5" mdtype="table" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; background-color: rgb(255, 255, 255);">

28일(목)

  | 640호 | 525호 | 526호
-- | -- | -- | --
09:40 – 10:00 | AM/Variational  inference of the solution of stochastic partial differential equations |   |  
10:10 – 10:30 | AM/Trading  constraints in continuous-time Kyle models | PS/Positive  self-similar Markov processes obtained by resurrection |  
10:50 – 11:10 | PS/Optimal  investment in illiquid market with search fractions and transaction costs |   |  
11:30 – 11:50 | AM/Weighted  random cut forest algorithm for anomaly detection | SS-07/Quantum  divergences and optimization |  
13:10 – 13:30 | AM/Convolutional  neural network with topological data analysis for image classifications:  CNN-TDA net |   | SS-11
13:30 – 13:50 | AM/Proximal  linearized iteratively convex majorization-minimization method for nonconvex  and nonsmooth optimization problem |   | SS-11
13:50 – 16:30 |   |   | SS-11

</figure><p cid="n18" mdtype="paragraph" class="md-end-block md-p" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; caret-color: rgb(51, 51, 51); color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; background-color: rgb(255, 255, 255);"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;"></span></p>
<p style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"></p><p cid="n0" mdtype="paragraph" class="md-end-block md-p" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain md-expand" style="box-sizing: border-box;"></span></p><figure class="md-table-fig md-focus" cid="n5" mdtype="table" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default;"></figure><p cid="n18" mdtype="paragraph" class="md-end-block md-p md-focus" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative;"><span md-inline="plain" class="md-plain md-expand" style="box-sizing: border-box;"></span></p><figure class="md-table-fig" cid="n103" mdtype="table" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default;">

29일(금)

  | 640호
-- | --
09:00 - 10:30 | FS-02
10:40 – 11:15 | PS/spectral  large deviations for sparse random matrices
11:25 – 12:00 | AM/Reaction  networks for a graphical description of biochemical systems

</figure>

시간표에 나와있는 대로, 지원한 인원들이 중계를 도울 예정입니다.

**Comment by cth127** [comment]
신청한 세미나가 수업이랑 좀 겹치는군요😅😅 준비해주셨는데 아쉽습니다.. 고생하셨습니다

**Comment by wy-july** [comment]
SS-11은 640호에서 진행됩니다. 당일 알려드려서 죄송합니다.

**Comment by invigorator96** [comment]
closing outdated events.
