### ISSUE TITLE
Project Earthquake: Update 

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#23]
Periodic update on this project.

@AIML-K/grads please comment any questions. I'll try addressing these in the lab meeting on 3/23.

**Comment by invigorator96** [comment]
당연한 것들이라 이미 포함하셨을 것 같지만...  무엇을 만드는 것이 목표이고 어디까지 진척되어 있는지 등의 디테일이 궁금합니다
