### ISSUE TITLE
상반기 연구활동 종사자 안전교육 (3/25 금 점심 -- optional)

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#27]
저한테는 들어야 한다고 연락이 왔네요.

학생분들도 마찬가지일까요? 그렇다면 혹시 모여서 세미나 형식으로 듣고 시험치고 끝낼까요? 의견 부탁해요.

**Comment by invigorator96** [comment]
아마 신입생은 신규안전교육이 따로 있고, 기존 인원은 온라인으로 직접 들어야 할 겁니다. 세미나 형식으로 듣는 것은 가능하나 하더라도 각자 계정으로 플레이를 다 돌려야 시험 응시가 가능합니다.

**Comment by d-h-lee** [comment]
BYOL 피자&음료수. 이번 금요일 점심때 시간되는 사람들은 함께 진행하도록 합시다.

**Comment by cth127** [comment]
이번주 금요일 12시엔 세미나 따로 없는지요?

**Comment by wheresmadog** [comment]
참석 원합니다

**Comment by liquoricej** [comment]
참석 희망합니다.

**Comment by cth127** [comment]
저도 참석하겠습니다

**Comment by d-h-lee** [comment]
> 이번주 금요일 12시엔 세미나 따로 없는지요?

11시-12시: @dkimds 연구원님의 패션과제 담당부분의 세미나가 있습니다. 

안전교육 런치는 그 뒤에 이어서 있습니다

**Comment by hamgcho** [comment]
좀 늦었지만 저도 참석 희망합니다..!

**Comment by wy-july** [comment]
참석하겠습니다.

**Comment by 2jaehyuk** [comment]
저도 참석하겠습니다.

**Comment by invigorator96** [comment]
저도 참가합니다~

**Comment by d-h-lee** [comment]
BYOB입니다. 본인이 원하는 마실것도 지참해주세요~

**Comment by d-h-lee** [comment]
BYOL = Bring Your Own Laptop. 안전교육 들으려면 랩탑 있어야 합니다

**Comment by d-h-lee** [comment]
다들 안전교육 이수 잘 했지요? 이슈 닫도록 하겠습니다
