### ISSUE TITLE
Slack Pro 계정 전환

### ISSUE THREAD

**Issue by cth127** [AIML-K/bamboo-forest#35]
연구실의 역사가 길어지면서 지난 메시지를 확인할 수 없는 이슈가 발생합니다.

Pro 계정으로 전환할 시 이런 limit이 사라지고, 

#25 에서 제기한 실시간 음성 회의 기능을 사용할 수 있습니다. (꼭 줌을 켜고 링크를 보내지 않아도 원 클릭으로 가능해진다면 활성화될 여지가 있다고 생각합니다.)

관련하여 Pro계정 전환 의사가 있는지 궁금합니다.

**Comment by dkimds** [comment]
찬성. 교육기관은 85% 할인해줘요. 85% 가격이 아니라.

**Comment by cth127** [comment]
https://slack.com/intl/ko-kr/help/articles/206646877-%EA%B5%90%EC%9C%A1%EC%9A%A9-Slack-%ED%95%A0%EC%9D%B8-%EC%8B%A0%EC%B2%AD

호오 좋은 플랜이군요. 그렴 인당 1달러 정도입니다

**Comment by cth127** [comment]
일단 보류됨에따라 닫겠습니다.
