### ISSUE TITLE
3월 넷째주 AIML-K Lab Meeting Abstract

### ISSUE THREAD

**Issue by okaybody10** [AIML-K/bamboo-forest#36]
3월 넷쨰주 AIML-K 랩미팅

- 매주 랩미팅마다 진행했던 이야기를 요약하고자 함.
     - 한 명의 인원이 그 날 나온 내용을 간략하게 정리
     - Issue를 이용하여 업로드 해주길 바람

- 금일 랩 미팅 진행 목차
     1.  Github 사용 (부제: Issue를 적극 활용하자)
          - Github는 대개 project를 clone하여 download 후 활용하기 위함
          - 많은 사람들에게 알려진 대표적인 기능 외에도 Issue 기능이 있는데, 이를 적극 활용 권장
          - 어떤 주제에 대해 이야기하고 싶거나, 무언가를 시작하고 싶을 경우 Issue - 우측 상단의 New Issue를 이용할 것
          - Issue를 open할 시 slack에도 알람이 감을 유의
          - Issue들을 남겨둠으로써 어떠한 일들이 발생하였을 때 어떤 해결과정을 밟아왔는지 볼 수 있고, 과거의 경험을 공유하며 더 좋은 해결책을 찾기 위함
     2. 상반기 연구활동 종사자 안전교육
          - [Bamboo-forest Issue](https://github.com/AIML-K/bamboo-forest/issues)
          - 3월 넷째주 금요일(3.25.) 상반기 연구활동 종사자 안전교육 예정 (Optional)
          - 이후 점심식사 등도 계획이 되어 있으니, 참여 희망자들은 **필히** 해당 Issue에 comment
     3. Big-file upload
          - [Bamboo-forest Issue](https://github.com/AIML-K/bamboo-forest/issues/13)
          - Github 같은 경우 code를 올리는 것이 요점
          - 즉 tremendous file들을 github에 업로드하기는 다소 곤란(like dataset)
          - 현 상황은 docker hub을 구현하여 사용 중이나 진입장벽이 꽤 높은 편
          - 링크만 있으면 public하게 접근할 수 있는 좋은 tool이 있으면 좋을 것 같음
               - good idea가 있으면 write comment
               - Project: Earthquake 진행 간 python의 gdown library와 fuzzy option을 활용하여 google drive에서 링크를 다운받는 방법도 사용 => 다만 오래 걸린다는 단점이 있음
     4. Git Branching guide
          - [Bamboo-forest Issue](https://github.com/AIML-K/bamboo-forest/issues/17)
          - 깃허브를 사용하는 방법에 대한 요약
          - 특히 branching 같은 경우 현 상황에 대해 여러 사람들이 같은 자료로 다른 작업을 한 후 merge를 할 때 아주 유용하게 활용 가능 (Pull-Request 이후 optional merge를 통해 병합)
          - 다만 해당 이슈의 링크가 사라져서 404 Error를 뽐내고 있는 중
     5. What's your R(Reward), A(Action), S(State)?
          - [Bamboo-forest Issue](https://github.com/AIML-K/bamboo-forest/issues/24)
          - 3월 셋째주 금요일(3.18.) Reinforcement learning에 대한 Seminor가 있었고, 그때 나온 R, A, S를 실생활에 접목하는 것
          - 실제로 현 상황에서 어떠한 액션을 취한 후, 그에 대한 보상을 받는 것은 우리가 일상을 살아가나는 것과 굉장히 유사
          - 해당 시간에 나왔던 여러 가지 이야기들을 곱씹어보면서 본인의 계획을 Remind 해보는 것도 good thinking
     6. Project: Earthquake Seminor
          - 해당 시간에 나왔던 여러 가지 이야기들은 글로만 적기보다는 교수님의 PPT 등이 함께 하면 좋을 것 같아, 생략하겠습니다..
          - 많은 선배님들께서 좋은 질문들을 주시고, 교수님께서 그에 상응하는 명쾌한 답변으로 견문을 넓히는데 많은 도움이 되었을 것이라고 믿어 의심치 않습니다.

==================================================================================
간략하게 나마 써보았는데, 혹시 추가 해야할 사항들은 comment에 작성하면 좋을 것으로 사료됩니다!
이렇게 쓰는 것이 맞는지도 모르겠지만, 일단 간략하게나마 제 style로 Abstract 해보았습니다.
많은 피드백 주시면 고쳐 나가도록 하겠습니다!! 감사합니다.

**Comment by cth127** [comment]
다른 issue를 언급할 때 #16 이런 식으로 샾이랑 issue number을 달기만 해도 링크가 생깁니다. 요약하느라 수고하셨습니다!
