### ISSUE TITLE
Setup docker registry in NAS

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#38]
현재 dockerhub에서 계정 추가가 되지 않아서 연구실 내부 조커 이미지 푸쉬/풀 작업이 일부 인원만 가능합니다.

도커헙에서 바로바로 안 고쳐주네요. 640호의 NAS에 docker registry를 운영할 수 있을까요?

#13 도 연관있습니다.

**Comment by wheresmadog** [comment]
현재 NAS의 세팅이 꼬여있는 상태인데(1), 이 부분을 먼저 해결해야 할 것 같습니다.

(1) storage pool이 두개로 분할되어있는 상태이고, 그 중에서도 한 개의 볼륨(14TB)만 동작하는 상태입니다.

**Comment by d-h-lee** [comment]
데이터가 있는지 확인 바랍니다 (스토리지풀, 그리고 풀에 등록 안된 HDD들 raw). 

데이터가 있다면, 스토리지풀 새로 묶기 전에 누구 데이터인지 확인 & 구조해주세요. 

@AIML-K/grads 나스 HDD에 직접 데이터 넣으신 분...?

**Comment by invigorator96** [comment]
저는 나스는 사용한 적 없습니다

**Comment by wheresmadog** [comment]
제가 오늘 확인했을 시점에는, NAS 안에 들어가있는 파일들은 제가 넣어놓은 것들 밖예 없습니다. 워크스테이션을 초기화 할 예정이라 잠깐 백업용도로 빼놓은 것과 biomedical data를 넣어놨는데, 가능하다면 portable SSD를 빌려서 다시 백업을 해놓고 싶습니다. 추가로, 연구실은 월요일 오후에 나갈 예정입니다.

**Comment by d-h-lee** [comment]
ㅇㅋ 그럼 나스 데이터 백업 완료되면 이어서 이야기해봐요

**Comment by wheresmadog** [comment]
필요한 NAS 데이터는 백업을 마쳤습니다. 남아있는 데이터는 지워져도 상관 없습니다.
