### ISSUE TITLE
3월 다섯째주(마지막주) 랩미팅 시간을 빌리게 되었습니다

### ISSUE THREAD

**Issue by JiyoonJ** [AIML-K/bamboo-forest#40]
교수님께 허락을 받고 랩미팅 시간 (수요일 오후 4시)에 시계열 세미나 간단한 발표와 곧 들어갈 회사에 대한 간단한 소개를 하겠습니다!
주제는 통계적인 모델 중 하나가 될 것 같습니다.

**Comment by d-h-lee** [comment]
1시간 통째로 필요한가요? 어느정도 시간이 필요한지 알려주세요

**Comment by JiyoonJ** [comment]
40분 정도 필요할 것 같습니다! 괜찮을까요?

**Comment by d-h-lee** [comment]
40분 좋습니다!

**Comment by cth127** [comment]
역시 닫겠습니다.
