### ISSUE TITLE
4월 첫째주 AIML-K Lab Meeting Abstract

### ISSUE THREAD

**Issue by okaybody10** [AIML-K/bamboo-forest#45]
먼저, 제가 중간에 이해하지 못한 부분이나 놓친 부분이 있어서 100% 완벽한 요약이 아닐 수 있습니다.
만일 다소 중요한 내용이 비어있다면 comment 달아주시면 감사하겠습니다. (__)

## Milestone 0: Lab Meeting schedule
- Weekly Meeting 시간 단축 및 일시 변경

| | As-IS | To-Be |
| :--------: | :--------: | :--------: |
| 시간 | 각 Meeting마다 60분 내지 90분 | 각 미팅마다 30분씩
| 일정 | Lab Meeting 이후 타 meeting 진행 | Lab Meeting을 마지막으로 진행

- 추가로 생각해보아야 할 사항
    * 그날 미팅이 있는 사람들은 모두 세미나실에 있다가, 각자의 미팅 시간이 되면 유동적으로 진행하는 것은 어떤가?
    * E.g. 오늘 A, B라는 미팅이 있으면 A 미팅이 진행하고 있는 도중에도 B 미팅 참석자들이 자리를 지키고 있는 것 (출입은 자유)

## Milestone 1: How many papers can you read? ( #43 )
- [문제의 리포짓](https://github.com/rosinality/ml-papers/tree/main/papers)
    - 실제 Abstract을 읽어보면... 좀 황당합니다.
- 연구를 하는 연구자들이 논문을 안 읽을 수는 없음
    - 논문을 안 읽겠다라는 건 학생이 공부를 하지 않겠다는 의미와 동일
    - 책이라는 자료도 있지만, 책은 독자들을 위해 저자들이 중요한 정보를 다듬은 아주 깔끔한 data들
    - 실제로는 이렇게 깔끔한 내용들이나 이론보다는 raw하게 있는 경우가 많음 
    - 그리고 이런 것들을 조금이나마 체험할 수 있는 자료가 논문
- 다만, 논문을 읽는다라는 것의 의미는?
    - 내가 이 논문을 직접 주도하여 이끌지는 않았지만, 연구자의 입장에서 생각(E.g. 어떤 방법을 어떻게 적용하여 연구 결과를 측정하였는지, 새로운 방법을 제시하였는지 기존의 것을 발전시켰는지, ...)
- 논문을 읽는 것에 대해 강제성을 부여하는 랩실도 있는데, 과연 이것이 유익한가에 대해서 생각해볼 필요가 있음
    - 강제성을 부여한다는 것은 반대로 그러한 강제성이 없으면 읽지 않는 것인데, 마냥 좋은 것은 아님
    - 만일 논문을 읽고 발표를 하게 되면 논문을 읽는 것보다 발표 자료를 준비하는 것에 시간을 쏟을 수 있음. (배보다 배꼽이 더 커지는 상황)
    - 진행하게 되면 사람마다 관심 분야가 다 다른데, 이에 맞추면 발생하는 문제에 대해서도 고려사항
- 추후 추가 논의 예정

## Milestone 2: Repository Naming Rule ( #42 )
- 금일 랩미팅 도중 Closed된 issue
- 현재 repository가 너무 많이 있고, Naming convention이 따로 없어 지저분하게 보이는 상황
- 현재 진행하고 있지 않은 repository 같은 경우 폐기 예정
- 현재 진행하고 있는 repository(e.g. M3D-VTON) 같은 경우 이름을 변경할 예정
    - 이름을 변경하게 되면 이미 pull한 것들에 대해 조작 후 commit 등을 하면 에러를 도출하게 됨
    - 대처방법으로는 1) git command line 명령으로 git remote set-url 사용하면 됨 [예시링크](https://devconnected.com/how-to-change-git-remote-origin/) 또는 2) 새로 git clone 하는 방법이 있음 (Comment 참고)
- {project name}-alpha로 명명이 되면, 하위 항목들에 대해서는 Readme.md에 전부 작성할 예정

## Milestone 3: Setup docker registry in NAS ( #38 )
- 현재는 NAS를 활용 중이며, NAS 내에 docker repository를 만들고 일정 주기마다 docker hub로 백업을 하는 식으로 운영할 예정
- NAS 외에도 FTP를 사용하는 것에 대한 Idea도 나왔는데, 두개의 장단점이 뚜렷하여 무엇을 선택해야 할 지는 다소 고민되는 사항
- 논외로, Dockerhub.com이 일을 좀.. 잘하고 있는 것 같지는 않음..

## Milestone 4: Update lab member intro ( #44 )
- (랩 홈페이지)(https://dhl.korea.ac.kr)
- 사이트 내의 연구실 멤버를 업데이트 해야하는데, 어떤 내용을 작성해야 할 지  이슈로 가서 comment로 남겨 주길 바람.

**Comment by cth127** [comment]
엇 scribe 역할에 대해 기억을 못 하고 있었는데 재혁 씨가 정리해주셨군요 😀

**Comment by d-h-lee** [comment]
> 대처방법으로는 github shell에서 remote 명령어를 이용하여 바꿔주거나 아예 새로 pull을 하는 방법이 있음

대처방법으로는 1) git command line 명령으로 `git remote set-url` 사용하면 됨 [예시링크](https://devconnected.com/how-to-change-git-remote-origin/)   또는 2) 새로 git clone

**Comment by d-h-lee** [comment]
> 논외로, Docker가 일을 좀.. 잘하고 있는 것 같지는 않음..

Docker는 잘 작동하는데.. dockerhub.com 얘들이 일을 잘 안함.

**Comment by okaybody10** [comment]
> > 논외로, Docker가 일을 좀.. 잘하고 있는 것 같지는 않음..
> 
> Docker는 잘 작동하는데.. dockerhub.com 얘들이 일을 잘 안함.

앗 이를 적고 싶었는데 잘못 작성하였습니다 ㅠㅠ 수정하겠습니다!
