### ISSUE TITLE
Update README.md in alpha repositories

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#46]
Include links to relevant repositories. See #38 and #45 

- [x] #47
- [ ] [earthquake-alpha](https://github.com/AIML-K/earthquake-alpha)
- [ ] [fashion-alpha](https://github.com/AIML-K/fashion-alpha)
- [x] [mathai-alpha](https://github.com/AIML-K/mathai-alpha)

**Comment by cth127** [comment]
mathai쪽 repo가 서로 일관되지 않은 작업을 목표로 하고 있는 문제가 있습니다.

- mathai-alpha: 수학 문제 풀이에서의 shortcut learning에 대한 대응방안 연구
- crosslingualMWP: 다국어 모델을 활용하여 언어 간 사칙연산 풀이 전이 연구
- crosslingualMWP + AGC2021: coling, 사칙연산 외의 연산 모델과 데이터 연구

사실 3번의 경우 별도의 repo를 파는 게 맞았는데 중간에 방향이 바뀐 영향으로 섞이게 되었습니다.. 이런 경우 별도의 alpha repo를 파는 게 맞을지, 아니면 일단 통합을 하는 게 맞을지 의견 여쭙고 싶습니다.

**Comment by wheresmadog** [comment]
upload navigator in fashion-alpha but only as a draft, detailed descriptions are needed
