### ISSUE TITLE
How to use private registry running on NAS instead of DockerHub

### ISSUE THREAD

**Issue by wheresmadog** [AIML-K/bamboo-forest#51]
For more details, you can read [here](https://docs.docker.com/registry/deploying/#copy-an-image-from-docker-hub-to-your-registry).

This issues explains about using NAS as a docker registry. I assume that a reader already is so familiar with `docker` and `registry` that one can freely `docker pull` and `docker push` as needed.

In usual cases, one push/pull an image into/from DockerHub only with the name and tag of an image, e.g., `docker pull ubuntu:18.04`. However, the command is merely an alias of `docker pull docker.io/ubuntu:18.04` where `docker.io` is nothing but an address of DockerHub. Analogously, should one has a private registry and its valid address with access, `docker push <address>:<port>/<image_name>:<tag>` will push an image into the designated registry. For this:

- Rename your image
```
docker tag <image>:<tag> <address>:<port>/<image_name>:<tag>
```
- Push into your registry
```
docker push <address>:<port>/<image_name>:<tag>
```
- Or pull
```
docker pull <address>:<port>/<image_name>:<tag>
```

NOTE: Such process should give you an error because of your docker cli is unsure whether or not the registry you are trying to request is safe. To resolve this, you MAY configure your docker daemon - `dockerd`.
- Go to a directory where `daemon.json` locates, by default:
```
cd /etc/docker/
```
- Open `daemon.json` with your text editor such as `vim` or `nano`
- Add line
```
{
    "runtimes": { ...
    },
    "insecure-registries":[<address>:<port>, ...]
}
```
- Restart your docker. WARNING: Having a process ongoing in a container, you should save your works before restart docker.
```
sudo systemctl restart docker
```

**Comment by wheresmadog** [comment]
For the valid address and port to reach out a private registry, you can refer the board behind my seat, or simply ask me in person.

**Comment by invigorator96** [comment]
@wheresmadog following this document, the docker failed to be started. It returns error on docker daemon. Seems issue on `daemon.json`, because reverting the change restored the docker service. Can you share your docker version for the troubleshooting? Note that mine is `Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3`.

**Comment by invigorator96** [comment]
nvm. resolved. Suggest to change 
```sh
{
    "runtimes": { ...
    },
    "insecure-registries":[<address>:<port>, ...]
}
```

to

```sh
{
    "runtimes": { ...
    },
    "insecure-registries":["<address>:<port>", ...]
}

the IP_address:port information should provided by string.
```

**Comment by d-h-lee** [comment]
https://github.com/AIML-K/aimlk-readme/ 이쪽 리포로 세부 정보를 이동하는것을 추천합니다
