### ISSUE TITLE
4-5-6월 생일파티

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#52]
를 5월 18일 랩미팅때 진행하려 합니다. 해당 생일자들은 코멘트 달아주세요.

혹시 올해 이미 생일이 지났는데 기회를 놓쳤어도 알려주세요

**Comment by pinga999** [comment]
6.15 생일입니다...!

**Comment by hyunsanghwang** [comment]
6.1 생일입니다.

**Comment by hamgcho** [comment]
6월 8일 생일입니다!
