### ISSUE TITLE
Github can display LaTeX (MathJax)

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#56]
Find $C, O, F, E, T, H, R, M \in [10]$ such that

$$ COFFEE + COFFEE + COFFEE = THEOREM $$

Verbatim version is:
```
Find $C, O, F, E, T, H, R, M \in [10]$ such that

$$ COFFEE + COFFEE + COFFEE = THEOREM $$

```

Note double dollars (full line version, needs a newline before it) and single dollar (inline version) work differently.

**Comment by invigorator96** [comment]
Not available for github mobile... 😞
