### ISSUE TITLE
Dinner Party (Jun 29 6:30PM- / 성수동 문츠바베큐 / 고기)

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#57]
We will have a lab dinner party. Time, location, whatabouts are all up for discussion!

- Suggested date: Jun 28, 29, or 30 (Tue, Wed, or Thu)
- Suggested location: ?
- What to do/bring/whatelse: ???

**Comment by invigorator96** [comment]
29일 랩미팅 끝나고 다같이 출발하면 어떨까요?

**Comment by d-h-lee** [comment]
네네. 29일 저녁, 성수동 근처(아마도 문츠바베큐)로 가려고 합니다. 참석하실 분들 여기에 답 달아주세요!

**Comment by wheresmadog** [comment]
✋

**Comment by hamgcho** [comment]
참석 희망합니다!

**Comment by hyunsanghwang** [comment]
참석 희망합니다.

**Comment by cth127** [comment]
참석합니다~

**Comment by invigorator96** [comment]
참석합니다~!

**Comment by wy-july** [comment]
참석하겠습니다.

**Comment by 2jaehyuk** [comment]
참석합니다!

**Comment by liquoricej** [comment]
참석합니다!

**Comment by JiyoonJ** [comment]
저도 참석하겠습니다~

**Comment by hsh6449** [comment]
참석하겠습니다~

**Comment by d-h-lee** [comment]
여기까지 11명 + @d-h-lee + @prism4304  해서 13명. 

29일 저녁 6:30 문츠바베큐 (https://app.catchtable.co.kr/ct/shop/moonts) 예약했습니다.
