### ISSUE TITLE
Introductory presentation for beginners in Python

### ISSUE THREAD

**Issue by hyunsanghwang** [AIML-K/bamboo-forest#66]
Hello I would like to hold an introductory presentation for beginners in Python.

I am a graduate student currently under advision of Professor Euisung Park and am interested in pure mathematics. For some time, I have experienced certain gaps between studying mathematics and computer science.

Although I am still at a learning level, I wish to share my personal experiences in learning Python and assist those who may experience the difficulties I had during the very first steps of learning Python.

It will be in the perspective of someone who has to learn the language in a hurry. And since these tips are for a beginner level, they may not be exclusive to Python only.

It would be best if I could make this presentation in front of (not necessarily physically) those who could benefit from this presentation. If you are interested, please let me know by commenting here or through Slack messenger. I hope to find a time that suits the most people.

Please understand that for personal reasons, I can schedule this presentation no later than the third week(15-19) of August.

Thank you.

**Comment by yeobinhong** [comment]
안녕하세요
발표 관심 있습니다!

**Comment by okaybody10** [comment]
발표 관심있습니다!

**Comment by hyunsanghwang** [comment]
@yeobinhong @okaybody10 두 분 모두 관심 가져주셔서 감사드립니다. 가능하다면 두 분 모두 참석 가능한 시간대에 슬롯을 잡아보고 싶은데 이번 달 20일과 27일 중에 세미나 참석 못 하시는 날이 있나요?

**Comment by yeobinhong** [comment]
> @yeobinhong @okaybody10 두 분 모두 관심 가져주셔서 감사드립니다. 가능하다면 두 분 모두 참석 가능한 시간대에 슬롯을 잡아보고 싶은데 이번 달 20일과 27일 중에 세미나 참석 못 하시는 날이 있나요?

저는 회의 시간 제외하고 다 가능합니다!

**Comment by d-h-lee** [comment]
@jhy4277 recommended

**Comment by okaybody10** [comment]
> > @yeobinhong @okaybody10 두 분 모두 관심 가져주셔서 감사드립니다. 가능하다면 두 분 모두 참석 가능한 시간대에 슬롯을 잡아보고 싶은데 이번 달 20일과 27일 중에 세미나 참석 못 하시는 날이 있나요?

저는 월, 수 가능합니다.

**Comment by jhy4277** [comment]
안녕하세요 저도 관심있습니다! 7월중에 본가에 가는 기간이 있어서 온라인으로 참석해도 될까요?

**Comment by hyunsanghwang** [comment]
> 안녕하세요 저도 관심있습니다! 7월중에 본가에 가는 기간이 있어서 온라인으로 참석해도 될까요?

관심 가져주셔서 감사합니다. 그렇게라도 들어주시면 저야 감사하죠 😄

**Comment by hyunsanghwang** [comment]
@jhy4277 @okaybody10 @yeobinhong 안녕하세요. 7월 22일 11시에 발표를 진행하고자 하는데 괜찮으신가요?

장소는 수학과 세미나실이 되겠지만 온라인으로 참석하실 분들을 위해 줌으로도 송출하겠습니다.

**Comment by yeobinhong** [comment]
네!! 괜찮습니다

**Comment by okaybody10** [comment]
> @jhy4277 @okaybody10 @yeobinhong 안녕하세요. 7월 22일 11시에 발표를 진행하고자 하는데 괜찮으신가요?
> 
> 장소는 수학과 세미나실이 되겠지만 온라인으로 참석하실 분들을 위해 줌으로도 송출하겠습니다.

저도 문제없습니다!

**Comment by jhy4277** [comment]
저도 좋습니다!!

**Comment by okaybody10** [comment]
혹시 줌 링크 알 수 있을까요??
