### ISSUE TITLE
2022.08.10 Town Hall Meeting 

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#69]
Has the meeting been taking place while I'm away? This week, I'll join as well.

- When: 5PM on Wednesday, Aug 10. 
- Where: the usual zoom & ASB 526

Preparations

- [x] Reserve ASB 526 and set up audio&video

Agenda

- [ ] ASB640 layout update with workstation racks
- [ ] Let's define the roles and responsibilities of "방장"
- [ ] Who wants to be "방장" in fall 2022 semester (2022.9~2023.2)?

**Comment by d-h-lee** [comment]
Anyone in @AIML-K/grads want to lead this town hall meeting?

**Comment by cth127** [comment]
앗... 저는 미팅 없을줄알고 잡아놓은 일정이 있어서 참석이 어렵습니다..

**Comment by liquoricej** [comment]
저도 수요일 미팅이 없을 줄 알고 지난주에 금일 일정을 잡아서 참석이 어려울 듯합니다 😢

**Comment by d-h-lee** [comment]
8월 타운홀미팅: 수요일 12(정오)부터.
