### ISSUE TITLE
08.24 and 22-2 semester's town hall meeting

### ISSUE THREAD

**Issue by pinga999** [AIML-K/bamboo-forest#71]
2학기 타운홀 미팅 시간 확정이 필요한 때가 온듯 합니다!

불가한 요일,시간대 적어주시면 취합해보겠습니다!

**Comment by wheresmadog** [comment]
I'm okay with anytime after 3PM.

**Comment by cth127** [comment]
저는
월, 수: 오전x
화, 목: 오전x, 17시 이전 x
금: 14시 이후 x
입니다.

**Comment by 2jaehyuk** [comment]
저는
월, 수: 오전x
수: 5시 이후 x
화, 목 : 3시30분 이후 가능 입니다.

**Comment by hamgcho** [comment]
저는 월 수 오전,
화 목 : 오전 x, 오후 15시~17시,
금 15시 이후 제외하고 모두 가능합니다.

**Comment by pinga999** [comment]
월 : 오전불가
화 : 4시-6시가능
목 : 4시-6시가능
수 : 오후가능
금 : 오후가능
입니다

**Comment by invigorator96** [comment]
저는 모든 시간대 가능할 듯 합니다

**Comment by okaybody10** [comment]
저는
월: 불가
화: 11시 ~  15시
수: 12시 ~ 15시 / 18시 이후 다 가능
목: 11시 ~  15시 / 16시 45분 ~ 18시 가능
금: 모두 가능
온라인으로 참여시 목요일 19시까지 가능합니다!

**Comment by liquoricej** [comment]
저는 제약 없습니다

**Comment by pinga999** [comment]
> 저는 월: 불가 화: 11시 ~ 15시 수: 12시 ~ 15시 / 18시 이후 다 가능 목: 11시 ~ 15시 / 16시 45분 ~ 18시 가능 금: 모두 가능 온라인으로 참여시 목요일 19시까지 가능합니다!

수요일 15시부터 일정이 있으신거죠?

**Comment by okaybody10** [comment]
> > 저는 월: 불가 화: 11시 ~ 15시 수: 12시 ~ 15시 / 18시 이후 다 가능 목: 11시 ~ 15시 / 16시 45분 ~ 18시 가능 금: 모두 가능 온라인으로 참여시 목요일 19시까지 가능합니다!
> 
> 수요일 15시부터 일정이 있으신거죠?

넵 15시 30분부터 일정이 있습니다...

**Comment by d-h-lee** [comment]
@pinga999 의견취합 고마워요. 스케쥴 공유해줘서 고맙습니다. 수강신청 정정기간이 끝나면 확정가능하겠지만, 객관식 선택지로 하면:

- 수 15-16
- 수 16-17
- 목 17-18

인건가요?

**Comment by pinga999** [comment]
> @pinga999 의견취합 고마워요. 스케쥴 공유해줘서 고맙습니다. 수강신청 정정기간이 끝나면 확정가능하겠지만, 객관식 선택지로 하면:
> 
> - 수 15-16
> - 수 16-17
> - 목 17-18
> 
> 인건가요?

현재 상황으론 그렇습니다만, 수요일의 경우에는 성재혁학생이 15:30부터 수업이있다고합니다

**Comment by pinga999** [comment]
09.07기준으로 매주 목요일 17:00~이후의 526 공간대여를 완료해두었습니다.

Town hall 미팅 시간조율이 다시 발생하기 전까지는 이슈 닫아놓도록 하겠습니다
