### ISSUE TITLE
구글드라이브 종료 --> 어디로?

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#73]
연구실 공용으로 사용하던 구글드라이브 문서/폴더들이 없어질 위기입니다. (9월 중/하순?)

공용문서고가 필요하니 어디론가 옮겨가야 할것같은데, 대안을 이야기해보도록 합시다.

**Comment by invigorator96** [comment]
학교에서 제공하는 office365는 계속 쓸 수 있는 것으로 압니다. 이쪽 공유문서로 옮기는 것은 어떨까요? (이렇게 되면 onedrive 기반으로 가는 모양이 됩니다.)

아니면, 이제 메일 서비스를 네이버로 옮긴다고 하는데 그쪽에도 비슷한 기능을 하는 것이 있다고 알고 있습니다.

**Comment by wheresmadog** [comment]
개인적으로는 네이버 서비스가 어떨까 합니다 원드라이브는 좋은 기억이 별로 없네요...
