### ISSUE TITLE
AGC regular meeting을 위한 시간표 취합 (ASAP)

### ISSUE THREAD

**Issue by pinga999** [AIML-K/bamboo-forest#75]
AGC와 관련해서 regular meeting시간을 잡기위해
정정기간도 끝난것에 겸하여  어느정도 다시 시간 취합을 해보려합니다

다들 본인이 참여**불가능**한 시간을 적어주세요

ex
> 한영 : 월 15시이전, 화 19시이후

감사합니다!

**Comment by cth127** [comment]
미팅 시간 다음과 같이 정해졌습니다.

월: 15시 30분
목: 17시
금: 12시

**Comment by pinga999** [comment]
우선적으오 fix된걸까요?

**Comment by d-h-lee** [comment]
타운홀 미팅 끝나기 전에 신속히 처리하면 좋겠다는 이야기가 나와서 바로 정리했습니다!
