### ISSUE TITLE
2022.09.29 Town Hall Meeting Topics

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#76]
이야기하고싶은 토픽들을 코멘트로 달아주세요!

**Comment by d-h-lee** [comment]
- [ ] 10/7 내부 워크샵 시간표 짜기
- [ ] dockerhub 정비: COLING 전까지 완료목표로, 1) 기존 도커이미지 모두 백업, 2) 문제 있는 계정 철거, 3) 새로운 계정 시도 / 또는 로컬 NAS 사용

**Comment by cth127** [comment]
- [ ] 화학과제 쪽 인건비 확약서가 아직 안 들어왔는데 진행 사항이 궁금합니다.

**Comment by d-h-lee** [comment]
> [ ] 화학과제 쪽 인건비 확약서가 아직 안 들어왔는데 진행 사항이 궁금합니다.

방금 인건비 등록 재촉 연락을 넣었습니다. 저희가 직접 처리 못하는 상황이라 그래요;; 타운홀 미팅때 이게 대체 무슨 이상한 상황인지 설명해줄께요.
