### ISSUE TITLE
10/7 내부 워크샵 시간표 짜기

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#77]
Topic: AIML-K 2022 Fall Workshop @ Asan Science Building 526
Time: Oct 7, 2022 10:00 AM Seoul

워크샵 스케쥴 (10/6 버전 - 타임슬롯 확정, 발표자 확정) 

1. 10-11am: AIML-K talks: 차태훈, ?
3. 11-12noon: Undergrad talks AM: 성재혁, 정창해, 황산하
5. 12noon-1pm: MDS talks: 박지연, 이재혁
6. ~2pm: lunch
7. 2pm-3pm: Undergrad talks PM: 정혜원, 홍여빈
8. 3-4pm: Earthquake talks: 조근석, 한종원, ?
9. 4-5pm: Research proposal talks: 김양기, 김한영

워크샵 Talk Title 

- 차태훈: What I Learned from Success and Failure
- 성재혁: Transformer is God - Transformer on Graph Model
- 정창해: U2Net - PyTorch to TensorFlow
- 황산하: Deep Fashion AI: Image Segmentation of Clothes
- 박지연: Portfolio Optimization Based on the Adaptive Data Selection and Prediction using ML and DL
- 이재혁: Stylebot Story
- 정혜원: 어텐션을 사용한 인공 신경망 기계번역
- 홍여빈: Summer 2022 - Voice Phishing Text Detector
- 조근석: Generative Model for Seismic Data
- 한종원: Literature Survey on the Application of Deep Learning to Seismology
- 김양기: Understanding Deep Learning - In Perspective of Generalization
- 김한영: Text Summarization for News Sentiment Index

온라인 참여 주소:

Join Zoom Meeting https://korea-ac-kr.zoom.us/j/95967575514?pwd=ZERGQTVKVXUzUnRFOVZJd2w1L0xtUT09
Meeting ID: 959 6757 5514
Passcode: NdGP7yLiiF

발표에 대한 세부사항:

- 발표자료는 영어로 만듭니다 (학부학생은 영어/한글 선택가능)
- 발표는 우리말로 합니다 (영어발표 할 사람은 미리 알려주세요)
- 발표 주제 하나당 시간은 **최대** 20분 = 발표15분 + Q&A타임

스케쥴의 발표자 이름은 가나다순입니다. 스케쥴 관련 문의/요청사항은 코멘트로 해주세요.

_Originally posted by @d-h-lee in https://github.com/AIML-K/bamboo-forest/issues/76#issuecomment-1261622636_

**Comment by d-h-lee** [comment]
시작시간을 10am. 끝나는 시간을 뒤로 (10/7 colloquium 없음)

**Comment by d-h-lee** [comment]
학부학생들 talk을 오후시간으로 이동

**Comment by d-h-lee** [comment]
10/4 시간 재조정 (MDS talk 오전으로 조정, undergrad talks 오전/오후 세션으로 분리)

**Comment by wheresmadog** [comment]
조교 관련 미팅이 급히 생겨서 기존 일정에 변경이 있어야 할 것 같습니다.
- 16:30 ~ 17:00

**Comment by d-h-lee** [comment]
- [ ] PPT 최종본을 어딘가에 업로드
- [ ] PDF 본도 함께 업로드
- [ ] 구글드라이브 하나 파서, 업로드하고, 링크 공유
- [ ] 세션별/톡별 구글폼 만들어서 링크공유
- [ ] 피자 주문 -- 백진경선생님
- [ ] 일정홍보 -> 학부생?

**Comment by d-h-lee** [comment]
저번학기 세미나 다들 수고 많았어요! 이 이슈는 닫겠습니다~
