### ISSUE TITLE
2/1 individual meeting requested

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#86]
2월1일 (수요일) 미팅 요청 - 연구 진행상황 업데이트&논의 미팅입니다. 30분입니다. 

연구 진행상황 업데이트를 **간단히 슬랙DM으로 @d-h-lee 에게** 최대한 빨리 보내주고, 당일 사용할 자료들은 1/31까지 마찬가지 DM으로 보내주세요. 미팅 당일에는 먼저 10분정도 발표하고 나서 논의 들어갈 예정입니다. 

혹시 아래 일정이 안맞는 사람이 있으면 자체적으로 swap해서 고쳐주세요. 

- 오후1: 이재혁 @2jaehyuk 
- 오후2: ~~정우영 @wy-july~~ 김한영 @pinga999 
- 오후3: 전한솔 @liquoricej 
- 오후5(타운홀 이후): 김양기 @wheresmadog

**Comment by pinga999** [comment]
자료라는 게 어떤 것일지 감이 구체적으로 오지 않습니다.

어떤 것을 의미하시는지 예시나 설명을 좀 들을 수 있을까요?

**Comment by d-h-lee** [comment]
> 자료라는 게 어떤 것일지 감이 구체적으로 오지 않습니다.
> 
> 어떤 것을 의미하시는지 예시나 설명을 조금 들을 수 있을까요?

발표에 사용할 PPT나 문서 같은 보조자료입니다~

**Comment by pinga999** [comment]
자료라는 게 어떤 것일지 감이 구체적으로 오지 않습니다.

어떤 것을 의미하시는지 예시나 설명을 좀 들을 수 있을까요?

**Comment by d-h-lee** [comment]
@2jaehyuk @pinga999 @liquoricej @wheresmadog 미팅 수고했습니다. 각자 피드백 반영한 것을 @d-h-lee 로 DM 업데이트를 최대한 빨리 부탁합니다~
