### ISSUE TITLE
6층복도 화학의 냄새 이슈

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#87]
오늘 (2/1) 복도에서 시큼한 뭔가 화학의 냄새가 납니다. 혹시 다른분들도 그렇게 느껴지나요?

**Comment by invigorator96** [comment]
6층 복도 전체는 아니고 화학과쪽에서 조금 느껴지긴 합니다

**Comment by d-h-lee** [comment]
오늘도 꽤 나는군요. 옥상 방수공사 때문일까요..?
