### ISSUE TITLE
02/01 타운홀때 나온 TODO list

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#88]
- [x] 앰버스 서버 가동
- [x] #93
- [x] #90
- [x] 3월 AIMLK워크샵 담당자(2인) 해보고 싶은분 @d-h-lee DM보내주세요

**Comment by invigorator96** [comment]
> 앰버스  서버 가동

IP 발급받았습니다:

IP Address:163.152.40.180
Subnet Mask : 255.255.255.0
GateWay : 163.152.40.1
DNS Server : 163.152.1.1
Assist DNS Server : 163.152.11.6

**Comment by d-h-lee** [comment]
> IP 발급받았습니다:

[서버 매뉴얼](https://www.supermicro.com/manuals/superserver/4U/MNL-2302.pdf) 17페이지부터 설치, 25페이지부터 유지보수 챕터가 있어요. 

케이블 연결방법에 대해서는 딱히 안 나와있어서 납품처 (앰버스 -- 0505-232-7890)에 문의해두었습니다. 

<img width="651" alt="image" src="https://user-images.githubusercontent.com/55645287/216210231-90f8926e-ea64-4eeb-8e56-2f1a25645d12.png">
위 그림처럼 파워서플라이가 2+2로 되어 있는데, 각각 1000W씩 당길수있습니다. 그러니 멀티탭은 2개 필요 (하나당 2400W정도가 최대)합니다.

답신 오면 업데이트 할께요

**Comment by d-h-lee** [comment]
파워서플라이 연결은, 2개 선을 1개 멀티탭에 연결, 그리고 각 멀티탭은 다른 벽전원에 연결. 이렇게 하면 된다고 합니다. 벽전원이 (재수없게도) 한 라인으로 연결되어 있으면 단락 가능성이 있습니다만, 바깥방이랑 안쪽방 벽전원은 아마도 다른 것일거라고 믿고 가봅시다.

파워 위상 문제는 알아서 내부적으로 해결하나보네요.

**Comment by invigorator96** [comment]
> 파워 위상 문제는 알아서 내부적으로 해결하나보네요.

그러면 바로 설치해볼까요..?

**Comment by pinga999** [comment]
구매요청에 미색a4용지도 끼워넣을수 있을까요...?

**Comment by invigorator96** [comment]
> 앰버스 서버 가동

624호 바깥방쪽 포트는 너무 멀어서 사용 불가능. 벽면의 콘센트 2개(하나는 아래, 하나는 환풍기용) 사용해 일단 전원 on상태

### issues
- 네트워크 세팅이 아직 안 되어 있음. netplan쪽 yaml 파일 수정해서 재부팅은 했으나 ssh  접근 실패중.
  - 랜선 꽂는 포트가 여러개인데 1번이 아니라 0번에 꽂혀 있을 가능성

- 벽면 파워가 앰버스 서버를 감당할 수 있는지 알 수 없는 상태. 풀파워 사용은 자제할 필요성이 있음

**Comment by d-h-lee** [comment]
이번 워크샵 담당자 volunteer 2명의 연락을 받았습니다! @invigorator96 @wheresmadog 고마워요!
