### ISSUE TITLE
멀티탭, 미색 용지 구매건 

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/bamboo-forest#92]
택배 배송 완료되었다고 문자가 왔습니다. 위치가 이학관 1층일지, 이학관6층 제 연구실 앞일지 모르겠네요. 615호라고 상자에 쓰여있을텐데, 확인해서 가져와주길 바랍니다.

이번 구매한 멀티탭은 고용량 누전차단 버전입니다. 앰버스 서버에 사용할 수 있도록 선이 긴 것으로 주문했으니 장착 바랍니다.

종이는 무거우니까 들 때 조심하세요!

**Comment by invigorator96** [comment]
처리 완료했습니다. 멀티탭 두개는 앰버스쪽 멀티탭과 교체했고 남은 하나와 쓰던 멀티탭은 607에 보관했습니다.

종이의 경우 640 랙 옆에 배치해 두었습니다.


![20230216_161800.jpg](https://user-images.githubusercontent.com/66249471/219298279-1f4cabca-9d0e-413e-86b4-ebb04ad0540e.jpg)

![20230216_162612.jpg](https://user-images.githubusercontent.com/66249471/219298291-90734841-d886-4dd9-9fbd-6fc885a0dac7.jpg)
