### ISSUE TITLE
23-1학기 타운홀미팅 시간조율

### ISSUE THREAD

**Issue by pinga999** [AIML-K/bamboo-forest#96]
타운홀미팅 참여가 가능한 시간들을
요일별로 적어주시면 취합하겠습니다!

월 :  ~
화 :  ~
수 :  ~
목 :  ~
금 :  ~

+ 다가오는 다음주 타운홀 미팅은 (0301수요일이 공휴일인 관계로) 0228화요일에 당겨서 진행될예정입니다.

예정된 진행시간은 16-18시사이입니다 안되시는 시간이있으시면 별도로 코멘트 주세요

**Comment by hojun-y** [comment]
저는 미팅 가능한 시간이 아래와 같습니다.

- 월요일 : 시간 없음
- 화요일 : 12:00 - 15:00, 17:00 -
- 수요일 : 13:00 -
- 목요일 : 12:00 - 15:00
- 금요일 : 12:00 - 14:00, 15:30 -

**Comment by pinga999** [comment]
- 월요일 : 15시 이후
- 화요일 : 16시 이후
- 수요일 : 15시 이후
- 목요일 : 16시 이후
- 금요일 : 15시 이후

**Comment by wheresmadog** [comment]
- 월요일: 00:00~24:00
- - 월요일: 00:00~24:00
- - 월요일: 00:00~24:00
- - 월요일: 00:00~24:00

**Comment by cth127** [comment]
- 월요일: 12 ~ 16시 50분 사이 가능
- 화요일: 상관 없음
- 수요일: 12 ~ 16시 50분 사이 가능
- 목요일: ~ 16시 40분 가능
- 금요일: ~ 16시 가능

**Comment by okaybody10** [comment]
* 월요일 17시 이후
* 목요일 17시 이후
* 금요일 16시 이전

입니다.

**Comment by wy-july** [comment]
- 월요일 15시 이후
- 화요일 불가능
- 수요일 15시 이후
- 목요일 15시 이후
- 금요일 16시 이전

**Comment by invigorator96** [comment]
- 월요일 09:30~18:30
- - 월요일 09:30~18:30
- - 월요일 09:30~18:30

**Comment by invigorator96** [comment]
- 월요일 09:30~18:30
- 화요일 09:30~18:30
- 수요일 09:30~18:30
- 목요일 09:30~18:30
- 금요일 09:30~18:30

**Comment by liquoricej** [comment]
저도 언제든 상관없습니다.

**Comment by 2jaehyuk** [comment]
>목: 5시 이전
다른 요일은 모두 가능합니다

**Comment by pinga999** [comment]
교수님 강의시간
화,목 15:30~16:45 / 10:30~11:45
목 17:00~

**Comment by hamgcho** [comment]
- 월 : 12:00 ~ 17:00
- 화 : 10:00 ~ 14:00, 15:30 ~ 18:00
- 수 : 12:00 ~ 17:00
- 목 : 10:00 ~ 14:00, 15:30 ~ 18:00
- 금 : 10:00 ~ 17:00

가능합니다

**Comment by pinga999** [comment]
금요일 12-14시가 현재까진 전체가 참여가능한 시간입니다

**Comment by jungchanghae** [comment]
월 : 17시 이후
화 : 16시 이후
수 : 17시 이후

**Comment by d-h-lee** [comment]
월화수목금 중에서는 모두가 모일 시간이 안되는군요. 합리적인 의사결정과정을 거쳐 이렇게 ~~토요일 미팅~~이 시작되는 것인가요..?

이번주 금요일 리허설때 다들 모일테니, 그때 결정하도록 합시다.

코멘트 자유롭게 남겨줘요~

**Comment by hojun-y** [comment]
제가 미팅 가능한 시간이 변경되어 원래 써 놓았던 comment를 update했습니다.

**Comment by d-h-lee** [comment]
모두 되는 시간이 월-금에 없습니다. 저번 가을학기처럼 수/금으로 split하도록 할까요?

예시:
- 수요일 오후 (15:00-) 의 _______
- 금요일 점심 (12:00-) 의 피자타임

**Comment by hojun-y** [comment]
그렇다면 저는 금요일 12PM slot에 참여할 수 있을 것 같습니다.

**Comment by invigorator96** [comment]
찬성합니다~

**Comment by pinga999** [comment]
> 모두 되는 시간이 월-금에 없습니다. 저번 가을학기처럼 수/금으로 split하도록 할까요?
> 
> 예시:
> 
> * 수요일 오후 (15:00-) 의 _______
> * 금요일 점심 (12:00-) 의 피자타임

수요일 15:00- 공간대여 신청해둘까요?

**Comment by d-h-lee** [comment]
> 수요일 15:00- 공간대여 신청해둘까요?

넵!
 
-----

> 수요일 오후 (15:00-) 의 _______
> 금요일 점심 (12:00-) 의 피자타임

위 두 시간대를 고정으로 해 두고, 참석 가능한 사람들이 모여서 이야기, 그리고 팔로업 필요한 것들은 이슈로 올려서 진행. 

굳이 미팅까지 기다리지 않고 진행될 이슈들은 저 시간대 상관없이 진행 바랍니다.

**Comment by pinga999** [comment]
> > 수요일 15:00- 공간대여 신청해둘까요?
> 
> 넵!
>  
> -----
> 
> > 수요일 오후 (15:00-) 의 _______
> > 금요일 점심 (12:00-) 의 피자타임
> 
> 위 두 시간대를 고정으로 해 두고, 참석 가능한 사람들이 모여서 이야기, 그리고 팔로업 필요한 것들은 이슈로 올려서 진행. 
> 
> 굳이 미팅까지 기다리지 않고 진행될 이슈들은 저 시간대 상관없이 진행 바랍니다.

금요일시간도 신청을 해두라는뜻이지요?
