### ISSUE TITLE
Workshop: Rehearsal Schedule

### ISSUE THREAD

**Issue by wheresmadog** [AIML-K/bamboo-forest#99]
Time: Fri, 12:00~
Location: 526

Please prepare your presentation for rehearsal.
@cth127 @invigorator96 @liquoricej @pinga999 @wheresmadog @wy-july @hamgcho

**Comment by invigorator96** [comment]
> This schedule will be on 3/3?

Yes. It would be 3/3.

> Is it okay to present using zoom?

As I know, not recommended

**Comment by d-h-lee** [comment]
During the talk:
- All talks will be recorded for training purposes 
- Everyone will have exactly firmly absolutely 20 minutes to help review the timing
- During that 20 minute rehearsal no one will interrupt the talk (note -- this is not true at the 3/10 workshop)
- We will use the online feedback system for each talk

What you should do after the talk
- Thank everyone for the feedback
- Revise / prepare for the 3/10 workshop
- If you need, ask for another rehearsal (on demand, capacity limited)
